### ISSUE TITLE
Cannot connect to TorrentLeech.org

### ISSUE THREAD

**Issue by benyjr** [SickRage/sickrage-issues#263] opened 2015-12-18 17:02 UTC
Hi,

I opened a TorrentLeech account and I entered my username and password into SickRage, but it won't connect:

```
2015-12-18 11:20:24 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: Transaction with 2 queries executed
2015-12-18 11:20:24 WARNING  SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: Unable to connect to provider
2015-12-18 11:20:24 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [TorrentLeech] :: Requested getURL https://torrentleech.org/user/account/login/ returned status code is 403: Forbidden
```

However if I got to https://torrentleech.org/user/account/login/ in a browser, the login page is working fine.

Has TorrentLeech.org banned SickRage from connecting?

**Comment by SickRage2** [comment] 2015-12-18 17:02
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)
- [ ] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by duramato** [comment] 2015-12-18 17:07
It seems like ai also cant connect `[TorrentLeech] :: Requested getURL https://torrentleech.org/user/account/login/ returned status code is 403: Forbidden`
@SickRage/moderators Any one can confirm?

**Comment by labrys** [comment] 2015-12-18 17:28
@duramato confirmed.. I believe this is a provider issue as I just tested this on multiple masters over the last 30 days and all failed with a 403.  I messaged the support staff but have not received a response.

@benyjr Please follow submission guidelines as indicated by the SickRage bot.  Wrap your log entries with \`\`\` and include the required basic information.

**Comment by benyjr** [comment] 2015-12-18 17:30
I will do so in the future. 

My apologies.

**Comment by duramato** [comment] 2015-12-18 18:07
For the record ```Requested getURL https://pretome.info/takelogin.php returned status code is 403: Forbidden```

**Comment by xtjoeytx** [comment] 2015-12-18 18:57
403 Forbidden: The owner of this website (torrentleech.org) has banned your access based on your browser's signature

The user-agent being sent is:
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.1 Safari/537.36Mozilla/5.0 (Windows NT 6.3; rv:36.0) Gecko/20100101 Firefox/36.0Mozilla/5.0 (X11; Linux i586; rv:31.0) Gecko/20100101 Firefox/31.0Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.75.14 (KHTML, like Gecko) Version/7.0.3 Safari/7046A194AMozilla/5.0 (iPad; CPU OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5355d Safari/8536.25Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; AS; rv:11.0) like GeckoMozilla/5.0 (compatible, MSIE 11, Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko

Changing the user-agent seems to solve the problem, seems cloudflare is restricting access based on the user-agent

**Comment by Rawa** [comment] 2015-12-18 20:37
This issue also affect sceneacess and hd-torrents

**Comment by Sjolus** [comment] 2015-12-18 23:01
+1 for Sceneaccess issue, can confirm on latest master and develop. Would be glad to provide any assistance if necessary.

**Comment by Sjolus** [comment] 2015-12-18 23:50
I took a look at the USER_AGENT being loaded from `common.py`, and tried with this, which worked perfectly:

```python
user_agents = [
    'Mozilla/5.0 (iPad; CPU OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5355d Safari/8536.25'
]
```

This seems to work for the SCC provider, but I can't really speak for the rest of the different providers. This is definitely a Cloudflare thing.

Original user_agents:
```python
user_agents = [
    'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36'
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.1 Safari/537.36'
    'Mozilla/5.0 (Windows NT 6.3; rv:36.0) Gecko/20100101 Firefox/36.0'
    'Mozilla/5.0 (X11; Linux i586; rv:31.0) Gecko/20100101 Firefox/31.0'
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.75.14 (KHTML, like Gecko) Version/7.0.3 Safari/7046A194A'
    'Mozilla/5.0 (iPad; CPU OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5355d Safari/8536.25'
    'Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; AS; rv:11.0) like Gecko'
    'Mozilla/5.0 (compatible, MSIE 11, Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko'
]```

The weird thing is that according to the code I'm reading, this shouldn't be used at all, it should default to the USER_AGENT with the SickRage ID in it unless I go for manually setting the spoof-variable to True in the code, but poking this user_agent list definitely makes stuff work anyway.

(Sorry if I'm not being clear enough, I'm definitely not a programmer, and I'm enormously new at this whole GitHub stuffamajigs. Ask me for more stuff and thou shalt receive)

**Comment by duramato** [comment] 2015-12-19 00:09
@Sjolus Setting the spoof to true didnt worked for me probably some ua from the list are blocked and others arent..

**Comment by Rawa** [comment] 2015-12-19 00:14
@duramato That might be true, I tried with same set up as @Sjolus enabling spoofing and only using ipad UA. Worked flawlessly.

**Comment by xtjoeytx** [comment] 2015-12-19 00:24
I don't know much of Python but I fixed it personally by adding comma's to
the user_agents array because they were being appended as a single string

**Comment by miigotu** [comment] 2015-12-19 00:26
orlly...

**Comment by xtjoeytx** [comment] 2015-12-19 00:30
@miigotu hehe your welcome :)

**Comment by miigotu** [comment] 2015-12-19 00:34
Fixed in develop -.- Aparently was my fubar like MONTHS ago

**Closed by miigotu** 2015-12-19 00:34 UTC
Labels: Confirmed, Support/Question

**Comment by Sjolus** [comment] 2015-12-19 01:15
Aaahahhaa, that explains it. I'm so blind. :dancers: GG fellas <3 Confirmed as functional.
