### ISSUE TITLE
Can't change branches from UI

### ISSUE THREAD

**Issue by djoole** [SickRage/sickrage-issues#59] opened 2015-11-22 23:35 UTC
From shell with command git checkout it works, but from UI (advanced settings), it tells : 

Update Failed
Update wasn't successful, not restarting. Check your log for more information.

Logs are here : http://pastebin.com/Fuw7G5Zw

**Comment by neoatomic** [comment] 2015-11-23 13:05
Sickrage isn't able to retrieve the newest commit. Meaning you haven't setup GIT correctly or did the wrong GIT commands. Or running Sickrage as the wrong user.?

` cur_commit = 271c94a7eede2c0f5b38f0fa4a040175cc63071a, newest_commit = `

**Comment by djoole** [comment] 2015-11-23 13:30
@miigotu seemed to say he was reproducing this issue yesterday..

It work when I do a git checkout develop/master... Doesn't that mean git is set up correctly?

**Comment by djoole** [comment] 2015-11-23 13:30
All sickrage files are owned by the user launching SR daemon

**Comment by djoole** [comment] 2015-11-23 13:31
Updates are working fine

**Comment by djoole** [comment] 2015-11-23 13:31
From GUI, I forgot to mention

**Comment by Koal4** [comment] 2015-11-26 19:36
I'm experiencing the same problem and I did a clean install of SR via synology package center because my old SR install didn't like switching repo and messed it up. Couldn't even update via Git.

Just for the record: with the old repo i didn't had any problems (automatic) updating or switching branch.

**Comment by miigotu** [comment] 2015-11-26 20:04
Switching branch on the old repo had the same exact issue. The updater does work. Dont compare us to a repo that is 1000 commits behind us.

**Comment by neoatomic** [comment] 2015-11-26 20:38
Running a Synology myself and have no problems at all. Just follow the guide below and you should be fine. 
(Only way i can explain those problems if you manually tried to manually switch with SSH.)

https://github.com/SickRage/sickrage-issues/wiki/Switching-your-Synology's-Sickrage-to-the-new-repository

**Comment by Koal4** [comment] 2015-11-26 21:04
@miigotu It's not like I switch brands on a daily basis. My reference about the old repo was just to make it clear i didn't experience any problems there along with other github apps I run. My point was not meant to compare SR (echelon) vs SR your team but only to address my git installation is working fine seeing that neoatomic suggested about it could be related to an incorrect git install.

@neoatomic 
Miigotu just confirmed that this problem (switching branch) is a bug which goes back to the old repo. So I find it strange that you don't have this problem unless you where referring to my update problem.

I followed this guide yesterday and as mentioned my SR install didn't liked it too much. I followed it to the letter but once I got my backup restored it couldn't update throough the GUI. I did a lot of troubleshooting, was even on irc for a while, thought I had it fixed untill new updates where pushed this afternoon and SR didn't wanted to update nor switch branch. I then started clean and installed SR via the synology package center and after a clean install I immediately tried to switch branch because at that time I thought the update/switch branch was problem was connected. But my update problem is not related to this problem about switching branches.

**Comment by djoole** [comment] 2015-11-27 00:41
So is this a confirmed bug?
Hearing @miigotu i think it is, but @neoatomic is not having this issue..

Updates are OK, so i guess Sickrage is able to retrieve the newest commit.

If, like neoatomic says, Sickrage isn't able to retrieve the newest commit, it's only when using the switch branch option, not update..

**Comment by miigotu** [comment] 2015-11-27 01:05
Just noticed that the restart page was borked on my last update on my production install (117 commits behind)....It shows a page saying too many redirects. I let it do its thing in the background and then reloaded the page manually in like 20 seconds and its fine.

**Comment by djoole** [comment] 2015-11-27 01:16
I've just updated (i was about 112 commits behind or so) and got a "too many redirects" too.
After reloading the UI loaded fine... but i still can't switch branches from UI, same error.

**Comment by miigotu** [comment] 2015-11-27 06:48
Switching branches is fixed in develop, will likely have onily a short release cycle again this week.

**Closed by miigotu** 2015-11-27 06:48 UTC
Labels: Support/Question

**Comment by djoole** [comment] 2015-11-27 07:06
Thank you!
