### ISSUE TITLE
unable to connect to sab

### ISSUE THREAD

**Issue by martinuk5** [SickRage/sickrage-issues#74] opened 2015-11-24 18:00 UTC
have only just started using sickrage after using sickbeard for years.

when i turn the computer on it snatches a few things but not all and comes back with an error.

2015-11-24 17:32:07 SEARCHQUEUE-BACKLOG-269613 :: [NZB.SU] :: Unable to connect to SAB: socket error : error [Errno 10061] No connection could be made because the target machine actively refused it

if i goto it and do a manual search it works fine so dont know why it doesnt snatch them straight away.

**Comment by labrys** [comment] 2015-11-24 21:08
@martinuk5 Can you help us out with some information, please.

DO NOT POST ANYTHING THAT CONTAINS YOUR LOGIN INFORMATION OR API KEY

Please include the following when opening a ticket :

Branch
Commit hash
Your operating system and python version
What you did
What happened
What you expected
How can we reproduce your issue
Include a link with your [log file](https://github.com/SiCKRAGE/sickrage-issues/wiki/FAQ's-and-Fixes#enable-debug-for-logs). (Not just a few lines!) And that has the error. Use [GIST](http://gist.github.com/) or [Pastebin](http://pastebin.com/)

**Comment by martinuk5** [comment] 2015-11-24 22:55
i am new to all this, as sickbeard didnt need all this installed and never used python before

i dont know what a branch is or a commit hash
im on windows 10 and python2.7
i told u what i did and what happened
that is all thats in my log file i dont know how to link you to it

**Comment by labrys** [comment] 2015-11-24 23:30
Branch is which branch you are on.. unless it was changed this should always be master.  The commit hash is a code that references which version of the software you are using.  Both can be found within SickRage : Go to the Gears in the upper right and click on Help & Info.

**Comment by labrys** [comment] 2015-11-24 23:38
The request I posted was just cut and pasted from the Issue readme, it's what we look for in any standard issue.   The log files can be pasted to either GIST or Pastebin listed in the links above.

**Comment by labrys** [comment] 2015-11-24 23:40
Just the message listed sounds like SABNZB isn't actively running but that's why a more complete log would be useful.

**Comment by labrys** [comment] 2015-11-28 14:50
Since an `Errno 10061` is an actively refused connection, it implies either the firewall refused it or SABNZB wasn't actively running.  Closing this issue.

**Closed by labrys** 2015-11-28 14:50 UTC
Labels: Support/Question

**Comment by martinuk5** [comment] 2015-11-29 08:57
i think sickrage is to fast when i start the computer up and runs before sabnzb has time to start. how can i change sickrage to startup later or do searches after an amount of time

**Comment by OmgImAlexis** [comment] 2015-11-29 09:17
@martinuk5 you shouldn't be shutting down either service. They're made to be running at all times. That's your problem.

**Comment by martinuk5** [comment] 2015-11-29 09:30
but i run it on a computer its all i have, so i have to turn the computer on and off each day

**Comment by OmgImAlexis** [comment] 2015-11-29 10:29
That isn't something we can really help with then, sickrage shouldn't be turned off at all. If it is then it's running in an unsupported way. @miigotu

**Comment by miigotu** [comment] 2015-11-29 10:32
@martinuk5 if it is windows, edit the service and set delayed start. If it is linux, add a sleep in the service file.
