### ISSUE TITLE
[APP SUBMITTED]: No JSON object could be decoded

### ISSUE THREAD

**Issue by MadBird** [SickRage/sickrage-issues#119] opened 2015-12-01 19:16 UTC
### INFO
Python Version: **2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010]**
Operating System: **Linux-4.2.0-18-generic-x86_64-with-Ubuntu-15.10-wily**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@1e8a1a0ede9b386f25e243c1c4e3814a520bd325
Link to Log: https://gist.github.com/a10771bcd65ea3cc7a87
### ERROR
```
SEARCHQUEUE-BACKLOG-76272 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by MadBird** [comment] 2015-12-01 19:16
### INFO
Python Version: **2.7.10 (default, Oct 14 2015, 16:09:02) [GCC 5.2.1 20151010]**
Operating System: **Linux-4.2.0-18-generic-x86_64-with-Ubuntu-15.10-wily**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@1e8a1a0ede9b386f25e243c1c4e3814a520bd325
Link to Log: https://gist.github.com/4c3cf5e53f08014a1a12
### ERROR
```
SEARCHQUEUE-BACKLOG-76272 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fernandog** [comment] 2015-12-01 19:23
@MadBird this provider is blocked for you? If not disable proxy for this provider.

**Comment by miigotu** [comment] 2015-12-01 22:02
@fernandog we dont have proxies anymore.

**Comment by OmgImAlexis** [comment] 2015-12-02 03:16
@miigotu maybe we need to add a log line suggesting they check if it's blocked, etc?

**Comment by miigotu** [comment] 2015-12-02 05:44
There already is a log line for that for kat and tpb. It is highly unlikely that TD is blocked. More likely is that TD was down during this error.

**Comment by mvarrieur** [comment] 2015-12-02 14:00
I and a couple others are having this issue with TorrentDay and a couple other providers (that all use the same API I'm fairly sure)

See here for reference:
https://github.com/SiCKRAGETV/sickrage-issues/issues/3731#issuecomment-161158488

I haven't tried switching to this repo yet, will be doing so tonight to see if the issue is fixed in the latest master here.

**Comment by labrys** [comment] 2015-12-02 14:07
@mvarrieur If it's not please let us know and we will look into it.

**Comment by polyneux** [comment] 2015-12-02 21:01
Labrys thanks for the help moving from the others. I was actually ALREADY using this repo which still causes the issue. I do not have TorrentDay but Speed.CD is pulling the same error. I'm new to this so I'm not sure if I should make a new issue or just comment here.

**Comment by labrys** [comment] 2015-12-03 02:45
@polyneux please make a new issue as different providers may be different issues. Thanks :smiley:

**Comment by miigotu** [comment] 2015-12-03 02:52
@labrys we try to keep the same provider issues in the same issue =P Our submitter even enforces that

**Comment by mvarrieur** [comment] 2015-12-04 00:31
I am now using this repo and having the same issue still. I'm 95% sure TorrentDay & SpeedCD (as well as some other providers) are the same site owner/API which is maybe why they broke at the same time. I'm personally only using SpeedCD and having the same issue here.

**Comment by miigotu** [comment] 2015-12-04 01:06
I will check TorrentDay later, but speed.cd I dont have an account for.

**Comment by mvarrieur** [comment] 2015-12-04 01:09
I found the issue for speed.cd I'm going to make a PR now, hopefully TorrentDay is a similar issue, but I don't have an account there.

**Comment by miigotu** [comment] 2015-12-04 01:20
TorrentDay works just fine here.

**Comment by MadBird** [comment] 2015-12-04 18:32
This happens on backlog searches even on the latest build. This has been happening for weeks, but did initially work.

On a daily search it pops out the following warning

    WARNING  SEARCHQUEUE-DAILY-SEARCH :: [TorrentDay] :: Unable to obtain cookie

Here is the full message from a backlog search

```AAValueError: No JSON object could be decoded
AA    raise ValueError("No JSON object could be decoded")
AA  File "/home/michael/.sickbeard/lib/simplejson/decoder.py", line 353, in raw_decode
AA    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
AA  File "/home/michael/.sickbeard/lib/simplejson/decoder.py", line 335, in decode
AA    return _default_decoder.decode(s)
AA  File "/home/michael/.sickbeard/lib/simplejson/__init__.py", line 307, in loads
AA    return json.loads(self.text, **kwargs)
AA  File "/home/michael/.sickbeard/lib/requests/models.py", line 802, in json
AA    return (resp.text, resp.content)[needBytes] if not json else resp.json()
AA  File "/home/michael/.sickbeard/sickbeard/helpers.py", line 1506, in getURL
AA    session=self.session, json=json, needBytes=needBytes)
AA  File "/home/michael/.sickbeard/sickbeard/providers/generic.py", line 138, in getURL
AA    parsedJSON = self.getURL(self.urls['search'], post_data=post_data, json=True)
AA  File "/home/michael/.sickbeard/sickbeard/providers/torrentday.py", line 115, in _doSearch
AA    itemList += self._doSearch(curString, search_mode, len(episodes), epObj=epObj)
AA  File "/home/michael/.sickbeard/sickbeard/providers/generic.py", line 330, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/home/michael/.sickbeard/sickbeard/search.py", line 495, in searchProviders
2015-12-04 11:26:46 ERROR    SEARCHQUEUE-BACKLOG-260449 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded
```

**Comment by AubreyKloppers** [comment] 2015-12-05 07:11
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.9**
Locale: unknown
Branch: **master**
Commit: SickRage/SickRage@c575707408313497ee391e761f0164fe574a3c6f
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-248834 :: [Speedcd] :: Error while searching Speedcd, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by AubreyKloppers** [comment] 2015-12-05 07:12
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.9**
Locale: unknown
Branch: **master**
Commit: SickRage/SickRage@c575707408313497ee391e761f0164fe574a3c6f
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-248736 :: [Speedcd] :: Error while searching Speedcd, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by AubreyKloppers** [comment] 2015-12-05 07:12
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.9**
Locale: unknown
Branch: **master**
Commit: SickRage/SickRage@c575707408313497ee391e761f0164fe574a3c6f
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-295557 :: [Speedcd] :: Error while searching Speedcd, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by AubreyKloppers** [comment] 2015-12-05 07:12
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.9**
Locale: unknown
Branch: **master**
Commit: SickRage/SickRage@c575707408313497ee391e761f0164fe574a3c6f
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-269602 :: [Speedcd] :: Error while searching Speedcd, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Closed** 2015-12-12 03:31 UTC
Labels: Support/Question

**Comment by Trapizomba** [comment] 2015-12-17 18:08
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@2eaf3fb24a465765d22d8ad8f0780d06a2b7ff89
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-281662 :: [HD4Free] :: Error while searching HD4Free, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Trapizomba** [comment] 2015-12-22 09:39
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@16646d679fbffdf948952722fba32867a596922d
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-73787 :: [HD4Free] :: Error while searching HD4Free, skipping: No JSON object could be decoded
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Trapizomba** [comment] 2015-12-27 11:15
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@dbf446a51f8b6e900aba41e947ef9f925ae12714
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-73787 :: [HD4Free] :: Error while searching HD4Free, skipping: No JSON object could be decoded [dbf446a]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by duramato** [comment] 2016-01-02 15:24
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@bc9b6dd4b21ba855e74dfb7b2a98231bc7c722ab
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-201641 :: [HD4Free] :: Error while searching HD4Free, skipping: No JSON object could be decoded [bc9b6dd]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Xenocell12** [comment] 2016-01-03 21:11
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-8.1-6.3.9600**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@4423fe95002315b812b4ef9867ea6df7d94c2083
Link to Log: https://gist.github.com/36fed608725562ffbc41
### ERROR
```
SEARCHQUEUE-BACKLOG-249235 :: [omgwtfnzbs] :: Error while searching omgwtfnzbs, skipping: No JSON object could be decoded [4423fe9]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by technazz** [comment] 2016-01-11 20:10
### INFO
Python Version: **2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7fd6c98aafe1f543bf8f96b2e370666be5412288
No Log available with ERRORS: 
### ERROR
```
SEARCHQUEUE-BACKLOG-72231 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded [7fd6c98]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by DeanBlackbeard** [comment] 2016-01-22 09:21
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@66fa37c556784fa3b41a06bb3043bd854d165c10
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-281511 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded [66fa37c]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by DeanBlackbeard** [comment] 2016-01-22 09:21
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@66fa37c556784fa3b41a06bb3043bd854d165c10
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-270668 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded [66fa37c]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by DeanBlackbeard** [comment] 2016-01-22 09:21
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@66fa37c556784fa3b41a06bb3043bd854d165c10
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-281536 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded [66fa37c]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by DeanBlackbeard** [comment] 2016-01-22 09:22
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@66fa37c556784fa3b41a06bb3043bd854d165c10
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-247808 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded [66fa37c]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by DeanBlackbeard** [comment] 2016-01-22 09:22
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@66fa37c556784fa3b41a06bb3043bd854d165c10
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-176941 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded [66fa37c]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by DeanBlackbeard** [comment] 2016-01-22 09:22
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@66fa37c556784fa3b41a06bb3043bd854d165c10
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-281630 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded [66fa37c]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by DeanBlackbeard** [comment] 2016-01-22 09:23
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@66fa37c556784fa3b41a06bb3043bd854d165c10
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-161461 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded [66fa37c]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by DeanBlackbeard** [comment] 2016-01-22 09:23
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@66fa37c556784fa3b41a06bb3043bd854d165c10
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-278125 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded [66fa37c]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by DeanBlackbeard** [comment] 2016-01-22 09:23
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@66fa37c556784fa3b41a06bb3043bd854d165c10
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-72108 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded [66fa37c]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by DeanBlackbeard** [comment] 2016-01-22 09:24
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@66fa37c556784fa3b41a06bb3043bd854d165c10
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-273402 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded [66fa37c]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by DeanBlackbeard** [comment] 2016-01-22 09:24
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@66fa37c556784fa3b41a06bb3043bd854d165c10
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-164541 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded [66fa37c]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by DeanBlackbeard** [comment] 2016-01-22 09:24
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@66fa37c556784fa3b41a06bb3043bd854d165c10
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-271910 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded [66fa37c]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by DeanBlackbeard** [comment] 2016-01-22 09:25
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@66fa37c556784fa3b41a06bb3043bd854d165c10
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-95451 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded [66fa37c]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by DeanBlackbeard** [comment] 2016-01-22 09:25
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@66fa37c556784fa3b41a06bb3043bd854d165c10
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-248736 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded [66fa37c]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by DeanBlackbeard** [comment] 2016-01-22 09:25
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@66fa37c556784fa3b41a06bb3043bd854d165c10
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-255316 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded [66fa37c]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by DeanBlackbeard** [comment] 2016-01-22 09:26
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@66fa37c556784fa3b41a06bb3043bd854d165c10
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-266189 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded [66fa37c]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by DeanBlackbeard** [comment] 2016-01-22 09:26
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@66fa37c556784fa3b41a06bb3043bd854d165c10
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-80379 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded [66fa37c]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by DeanBlackbeard** [comment] 2016-01-22 09:26
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@66fa37c556784fa3b41a06bb3043bd854d165c10
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-261690 :: [TorrentDay] :: Error while searching TorrentDay, skipping: No JSON object could be decoded [66fa37c]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
