### ISSUE TITLE
If only un-aired episodes the progres bar shows a `?`

### ISSUE THREAD

**Issue by neoatomic** [SickRage/sickrage-issues#15] opened 2015-11-19 11:17 UTC
This is an old bug. If a show has only un-aired shows that the progress bar in the banner layout shows a `?` instead of `0/0`.

Examples of shows are : `Lucifer` and `Deutschland 83`

![naamloos1](https://cloud.githubusercontent.com/assets/7928052/11269423/2c9d8164-8eb7-11e5-82dd-11176c8fcf4d.png)
![naamloos2](https://cloud.githubusercontent.com/assets/7928052/11269425/2c9e8852-8eb7-11e5-82f4-4958bca4d781.png)

```
SR Version: 	BRANCH: (develop) / COMMIT: (70ba9357c8dac3149405f0bcaf258593fe40fa9d)
SR User:	sickrage
SR Locale:	(None, None)
SR Config:	/usr/local/sickrage/var/config.ini
SR Database:	/usr/local/sickrage/var/sickbeard.db
SR Cache Dir:	/usr/local/sickrage/var/cache
SR Log Dir:	/volumeUSB1/usbshare/Temp
SR Arguments:	['--daemon', '--pidfile', '/usr/local/sickrage/var/sickrage.pid', '--config', '/usr/local/sickrage/var/config.ini', '--datadir', '/usr/local/sickrage/var/', '--nolaunch']
Python Version:	2.7.10 (default, Jun 3 2015, 20:43:13) [GCC 4.7.3 20130102 (prerelease)]
```

**Comment by OmgImAlexis** [comment] 2015-11-19 12:27
@neoatomic I can change that. I think it defaults to `?` as it doesn't have anything to base the count from. I think we can just assume if the `max_download_count` isn't set or is set to 0 that we should display 0/0, right?

**Comment by neoatomic** [comment] 2015-11-19 12:39
Sounds fine to me. @miigotu You also agree.?

**Comment by miigotu** [comment] 2015-11-19 13:13
sure why not. The ? was intended to be the way it is because we dont know how many episodes, so 0 works too I guess

**Comment by labrys** [comment] 2015-11-19 13:15
Or how about just blank?

**Comment by miigotu** [comment] 2015-11-19 13:17
Then it really looks more broken I think?

**Comment by OmgImAlexis** [comment] 2015-11-19 13:21
What about 0/0 and then the tooltip could say "This show hasn't aired yet" or "This show currently has no episodes"?

**Comment by labrys** [comment] 2015-11-19 13:23
I'd have to look at it.. and its not in front of me right now.  I think ? makes it look like something unknown happened, 0 would be better, but i think that doesn't really reflect what's going on either unless if you had some downloaded that weren't aired maybe 1/0 - You have one but zero have aired.. I like @OmgImAlexis 's recommendation with the tooltip.

**Comment by adaur** [comment] 2015-11-19 13:32
What about a N/A?

**Comment by labrys** [comment] 2015-11-19 13:33
I like N/A as well

**Comment by OmgImAlexis** [comment] 2015-11-19 13:37
I think N/A like ? would make people think there's something wrong with the show.. :confused:

**Comment by adaur** [comment] 2015-11-19 13:39
It's better than a question mark. It says non applicable, there is no information available atm

**Comment by miigotu** [comment] 2015-11-19 13:41
"Unaired"

**Comment by OmgImAlexis** [comment] 2015-11-19 13:42
@miigotu that's probably the best option.

@adaur we DO have info though. We know no episodes have aired.. :disappointed:

**Comment by fernandog** [comment] 2015-11-19 20:39
I think the 0/0 is better. so wont break the sorting too. ( or make easier to code it)

**Comment by OmgImAlexis** [comment] 2015-11-20 01:07
@fernandog the sorting is via a data element from memory. The visuals don't change the sorting order.

**Comment by labrys** [comment] 2015-11-28 14:44
I compromised with `0 / 0` on the progress bar and `Unaired` in the tooltip.  I thought the asthetics were better than `Unaired` or something else in the progress bar.  Closing for now, if anyone would like to revisit this we can re-open it later.

**Closed by labrys** 2015-11-28 14:44 UTC
Labels: Bug/Issue, Confirmed
