### ISSUE TITLE
Gui gets inaccessible after some time

### ISSUE THREAD

**Issue by MikeyMan83** [SickRage/sickrage-issues#428] opened 2016-01-06 20:22 UTC
Hello,

I recently switched to the non-tv branche, but this is still not functioning how i used to remember.

What happens is that the gui gets inaccessible after some time. The browser doesn't respond whatsoever. Only a stop-start will help. It seems -from the logs- that the fetching and searching is going as it should, but not having access to the gui (or via NZB360) is quite annoying.

I've tried pulling all updates. i also re-installed from scratch using a backup file. Still the issue persists.

I cannot find anything in the logs myself. Is this a known issue?

The general info is as follows:

Version: Branch: master
 Commit: 4eccee2ad1b3e3d144bfd8e315fdf397cfd33361
 Version: v5.1   
User: sickrage 
Locale: Language: None
 Encoding: None  
Configuration File: /usr/local/sickrage/var/config.ini 
Database: /usr/local/sickrage/var/sickbeard.db 
Cache Directory: /usr/local/sickrage/var/cache 
Log Directory: /usr/local/sickrage/var/Logs 
Arguments: ['--daemon', '--pidfile', '/usr/local/sickrage/var/sickrage.pid', '--config', '/usr/local/sickrage/var/config.ini', '--datadir', '/usr/local/sickrage/var/'] 
Python Version: 2.7.11 (default, Dec 17 2015, 12:58:48) [GCC 4.6.4] 

Gist link is: https://gist.github.com/MikeyMan83/0ced4d0156a739c2a6c1#file-gistfile1-txt

**Comment by SickRage2** [comment] 2016-01-06 20:22
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment] 2016-01-06 23:03
This is likely a situation where SR is not running but your service thinks it is.
Paste your startup/init script.

**Comment by MikeyMan83** [comment] 2016-01-07 07:32
Sounds strange to me. For instance, it was working fine before i went to bed, and this morning the issue was there. So it was running at some point.

I installed through the synology package center, via the sickrage package. Have to search where the startuo script is. Ill try that this evening.

**Comment by MikeyMan83** [comment] 2016-01-07 07:40
Also, after a restart, i see processing logs as late as 6:00 this morning.

**Comment by MikeyMan83** [comment] 2016-01-07 14:44
Could it be this file:

# SickRage
#
# Configuration Notes
#
#    - Adjust setuid and setgid to the user/group you want SickRage to run as.
#    - For all other settings edit /etc/default/sickrage instead of this file.
#
#      The following settings can be set in /etc/default/sickrage and are used to run SickRage.
#       SR_HOME=         #$APP_PATH, the location of SickBeard.py, the default is /opt/sickrage
#       SR_DATA=         #$DATA_DIR, the location of sickbeard.db, cache, logs, the default is /opt/sickrage
#       SR_OPTS=         #$EXTRA_DAEMON_OPTS, extra cli option for sickrage, i.e. " --config=/home/sickrage/config.ini"

description "SickRage Daemon"

start on runlevel [2345]
stop on runlevel [!2345]

kill timeout 30

setuid sickrage
setgid sickrage

respawn
respawn limit 10 5

script
    if [ -f /etc/default/sickrage ]; then
        . /etc/default/sickrage
    else
        echo "/etc/default/sickrage not found using default settings.";
    fi

    [ -z $SR_HOME ] && echo "I can't start SickRage if I don't know where it is"

    exec ${SR_HOME}/SickBeard.py -q --nolaunch --datadir=${SR_DATA-SR_HOME} ${SR_OPTS-}
end script

**Comment by MikeyMan83** [comment] 2016-01-08 13:16
Was this the right script? What else can i do to help a solution?

**Comment by neoatomic** [comment] 2016-01-08 14:42
@MikeyMan83 I have a Syno myself, and its running rock solid.

The GUI getting unresponsive is a bug on the old repo, so i'm wondering if you did correctly switch.
Did you follow this method.? https://github.com/SickRage/sickrage-issues/wiki/Switching-your-Synology's-Sickrage-to-the-new-repository

Also what amount of memory does your Syno have, and how much is used.?
It could be that a bad file is in your download folder and Postprosessing hangs on that file, but normally the log would have shown that.

And just to be sure, shutdown Sickrage and remove/rename the cache.db file, and remove the cache/sessions & cache/mako folders if they are there. And then restart SR. Maybe some bad cache from the old Repo got restored and is coursing this for you.

**Comment by MikeyMan83** [comment] 2016-01-08 15:12
@neoatomic Thanks for your response.

I actually tried both ways to migrate from repo. First i tried the git way. This didn't help. 
After that i made a backup of the files and reïnstalled exactly the way you described.

I have a DS414, not a base model.
It has 1GB of memory, of which -in rest, running all services- only 30-35% is used.

The processing and searching seems to be working just great.

I'll try to remove the cache files.

**Comment by neoatomic** [comment] 2016-01-08 15:43
Indeed the cache/sessions shouldn't be there, just wanted to make sure they indeed weren't. :) 
And make sure your monitored/download folder isn't containing any strange files.

Been browsing through your log a little, but cant find a real issue there.
I see your naming is like this `S01E12 - Fool Me Once` .? So its missing the shows name and quality.
If there is no quality found normally Sickrage will scan the file for its resolution, but that is only needed if you didn't download the files with SR itself.

Is there a way you could check at what time the GUI becomes unresponsive so i can check that time in your log.? That might give a hint where to search.

**Comment by MikeyMan83** [comment] 2016-01-08 17:44
I think the file naming is only used as output format isn't it? I don't like to have the quality displayed in explorer. Same with show name.
Hasn't been a problem in the year i've been using SR/SB now.

Think that the only way to find out when the gui becomes inresponsive is to log in every couple of minutes? No idea how else to do it...

**Comment by neoatomic** [comment] 2016-01-08 18:21
I'm pretty sure this isn't a Sickrage code issue but something local to your installation.
But than again i want to make sure, and also solve your issue.

You could check the GUI from time to time, doesn't have to be every minute. Its just so we can narrow it down a little.

But another option would be, installing another (new) instance of sickrage for testing.
As you are on a Synology, there is another package called sickbeard-custom, that you can use to install another instance of sickrage. So you have 2 sickrage installs running. 
(Installation works the same as the other package. just make sure you use the new Repo url)

* Do not restore a backup for that new install or change any settings. and see if the GUI still freezes.
* Then change/add the settings (again not restoring the backup!) , and check again if the GUI freezes. (As you already have the *.nfo files in you folders, adding your shows back will be apiece of cake.)

**Comment by MikeyMan83** [comment] 2016-01-08 19:59
It just broke down...  Was working fine two hours ago. 

Still... Seems strange to me that it would suddenly be an issue. Was working great before the issues with sickrage-tv started.

**Comment by miigotu** [comment] 2016-01-08 20:27
Also try removing cache.db, SRTV did corrupt some databases.

**Comment by SteveW25561** [comment] 2016-01-09 10:25
I also have the exact same issue, running on Synology as well as on a Mac.  Same symptoms that after an indeterminate time, accessing the GUI leaves the web browser spinning waiting for local host (on the Mac) or waiting for the Synology.  

I had recently installed fresh on Synology to give it a try and when it started freezing up, I decided to go back to running on my late 2015 5K iMac, with a fresh install there (restoring settings from a working backup).

Both the Synology and Mac were installed pointing to https://github.com/SickRage/Sickrage.git (Synology) and on the Mac with the command:
git clone https://github.com/SickRage/SickRage.git /Applications/SickRage

Both are on the same, current commit

Synology build:
Branch: master
Commit: 7fd6c98aafe1f543bf8f96b2e370666be5412288
Version: v5.1

Mac installation:
Branch: master
Commit: 7fd6c98aafe1f543bf8f96b2e370666be5412288
Version: v5.1

**Comment by neoatomic** [comment] 2016-01-09 14:24
@SteveW25561 See if you can also install a second instance of Sickrage with sickbeard-custom.
Dont change/add any settings or restore a backup there. Just let it run and see if it freezes.

**Comment by MikeyMan83** [comment] 2016-01-09 14:27
Just installed the second installation through sickbeard custom. 
I also see the python cpu usage quite high.

BTW; if i removed an reinstalled the app, shouldn't the failed.db en cache.db be renewed as well? Or ar these restored from backup?

**Comment by duramato** [comment] 2016-01-09 14:30
Failed is only when a failed download ocorrs and cache is when results are cached from inders afaik

**Comment by SteveW25561** [comment] 2016-01-09 19:23
@neoatomic thanks for the suggestion -- I'll try it and see although I can't see how to install another instance of Sickrage since the package center on Synology only shows "Open" for Sickrage (ie no "Install" option) since it's already installed.  Also, unsure of the actual URL for the sickbeard-custom.

Although you weren't able to reproduce the issue, I can say that on both my Synology and the Mac, after removing Pirate Bay from the torrent search providers, both installations are running fine and fully responsive (now about 8h), with python using only 0.1% on the Mac and 0% (sleeping) on Synology.  

I acknowledge it would be weird for a specific search provider to cause such problems (unless perhaps it's causing the episode search thread to hang for some reason), but it's the only thing I changed and it seems to be better right now...I'll try toggling it back on and see if it hangs again.

**Comment by neoatomic** [comment] 2016-01-09 19:45
@SteveW25561 It indeed sounds strange that removing TPB would solve it, but than again this isn't a normal problem... Let me know if it actually solves it, so we can look further into it.

@MikeyMan83 I see that you also use TPB, could you remove/disable that provider for testing.?

**Comment by SteveW25561** [comment] 2016-01-09 20:03
On the Mac, I re-enabled Pirate Bay with a custom URL to: 

Lo and behold, it froze again.  94% CPU usage for python.

Again, the last entry before restart was the  SEARCHQUEUE-DAILY-SEARCH

Log shows this:
```
2016-01-09 12:00:28 INFO     POSTPROCESSER :: Successfully processed
2016-01-09 12:00:28 INFO     POSTPROCESSER :: PostProcessing Path: /Volumes/Synology/Fresh/Sickrage
2016-01-09 12:00:28 INFO     TORNADO :: Starting SickRage on http://0.0.0.0:8081/
2016-01-09 12:00:28 INFO     MAIN :: Starting up SickRage [master] from '/Applications/SickRage/config.ini'
2016-01-09 11:44:37 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2016-01-09 11:44:36 INFO     FINDPROPERS :: [Rarbg] :: Searching for any new PROPER releases from Rarbg
2016-01-09 11:44:36 INFO     DAILYSEARCHER :: No new released episodes found ...
```

**Comment by labrys** [comment] 2016-01-09 20:10
@SteveW25561  Which may be why i haven't seen it as I don't run tpb.  Are you able to run tpb without a custom url for testing?

**Comment by labrys** [comment] 2016-01-09 20:20
I was able to duplicate it with TPB.  CPU usage on my pc hit 24% and stayed there on a single URL for over two minutes and counting on that single result during a backlog search.

**Comment by SteveW25561** [comment] 2016-01-09 20:36
Yep: now reproduced again on Synology: froze after re-enabling TPB using custom URL.

Synology Log:
```
2016-01-09 12:35:59 INFO     POSTPROCESSER :: Successfully processed
2016-01-09 12:35:59 INFO     POSTPROCESSER :: PostProcessing Path: /volume1/Synology/Fresh/Sickrage
2016-01-09 12:35:59 INFO     TORNADO :: Starting SickRage on http://0.0.0.0:8081/
2016-01-09 12:35:58 INFO     MAIN :: Starting up SickRage [master] from '/usr/local/sickrage/var/config.ini'
2016-01-09 12:35:58 INFO     MAIN :: Writing PID: 689 to /usr/local/sickrage/var/sickrage.pid
2016-01-09 12:35:58 INFO     MAIN :: Changing status from Archived to Archived (Unknown) for 283468: S02E08 at unknown location (File NOT FOUND)
2016-01-09 12:35:58 WARNING  MAIN :: Found 1 shows with bare archived status, attempting automatic conversion... [7fd6c98]
2016-01-09 12:22:18 INFO     POSTPROCESSER :: Successfully processed
2016-01-09 12:22:17 INFO     POSTPROCESSER :: PostProcessing Path: /volume1/Synology/Fresh/Sickrage
2016-01-09 12:22:01 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2016-01-09 12:22:01 INFO     DAILYSEARCHER :: No new released episodes found ...
```

On the Mac, without a custom URL, no freeze but I got the warning (which is why I used a custom URL in the first place):
```
2016-01-09 12:30:49 SEARCHQUEUE-DAILY-SEARCH :: [ThePirateBay] :: Connection error to getURL https://thepiratebay.ms/tv/latest?q=&orderby=7&category=200&type=search&page=0 Error: u'error ("bad handshake: Error([(\'SSL routines\', \'SSL23_GET_SERVER_HELLO\', \'sslv3 alert handshake failure\')],)",)' [7fd6c98]
```

**Comment by neoatomic** [comment] 2016-01-09 20:38
@SteveW25561 Nice work, this wasn't an easy to find. :+1: 

@labrys Unbelievable... And that without even trowing an error... 
At-least we know where to search now.

**Comment by labrys** [comment] 2016-01-10 01:42
This regex [thepiratebay.py#L66](https://github.com/SickRage/SickRage/blob/master/sickbeard/providers/thepiratebay.py#L66) is causing the problem when its being iter'd through at [thepiratebay.py#L93](https://github.com/SickRage/SickRage/blob/master/sickbeard/providers/thepiratebay.py#L93).  I think this only happens with no results.  Switching this provider to use beautiful soup should fix this.

**Comment by MikeyMan83** [comment] 2016-01-10 09:38
Ah, great. I indeed recently added a custom tpb URL.

Needless to say that the sickrage package was inaccessible this morning and the sickbeard custom was fine.

Removed the custom URL, let's see how it goes.

**Comment by MikeyMan83** [comment] 2016-01-11 11:17
Removing the link has seemed to be the fix!

**Comment by miigotu** [comment] 2016-01-11 15:59
Fixed in develop.

**Closed by miigotu** 2016-01-11 15:59 UTC
Labels: Bug/Issue, Confirmed

**Comment by filipkis** [comment] 2016-03-25 01:26
I had the same issue recently with my setup when I noticed that the problem was in `web_root` setting in `config.ini`. 

To be more precise, the setting was not the default one (I changed it) but I was accessing the web app on the old address (not including the additional web root) and that caused the problem.

Maybe this helps in debugging.
