### ISSUE TITLE
Skipped episodes are downloaded

### ISSUE THREAD

**Issue by pven** [SickRage/sickrage-issues#526] opened 2016-01-18 10:33 UTC
I am very sure I've set alle the episodes for this serie to 'Skipped'. Last week I was surprised some episodes were downloaded, while I was in doubt for a week (and changed the status to 'Skipped' again) it happened again.

Screenshot: http://static.tweakers.net/ext/f/8ASDOwB9oOAZyjjpSBw4OcPh/full.jpg

What is going on here?

**Comment by SickRage2** [comment] 2016-01-18 10:33
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by labrys** [comment] 2016-01-18 15:16
@pven We can't tell you whats going on without all proper information.  Please provide the required information requested by the SickRage bot.

**Comment by pven** [comment] 2016-01-18 15:29
Basic info
I am running on a synology.
Branch: master
Commit: af9a7fd04d3a80f16cc51ae9aa123fa1b452fd0c
Version: v5.1.2

What happened
Status voor serie is set to 'skipped', but episodes are downloaded anyway.

```
2016-01-18 12:55:26 INFO     SEARCHQUEUE-BACKLOG-77398 :: [Spotweb 2g] :: Performing episode search for The X-Files
2016-01-18 12:55:26 DEBUG    SEARCHQUEUE-BACKLOG-77398 :: [Spotweb 2g] :: Search Mode: Episode
2016-01-18 12:55:26 DEBUG    SEARCHQUEUE-BACKLOG-77398 :: [Spotweb 2g] :: Search string: The X-Files S01E01
2016-01-18 12:55:26 DEBUG    SEARCHQUEUE-BACKLOG-77398 :: [Spotweb 2g] :: Search URL: http://website.com/spotweb/api?apikey=**********&tvdbid=77398&season=1&maxage=2600&cat=5030%2C5040&
q=The+X-Files+S01E01&limit=100&t=tvsearch&offset=0&ep=1
2016-01-18 12:55:38 DEBUG    SEARCHQUEUE-BACKLOG-77398 :: [Spotweb 2g] :: Search string: X-Files S01E01
2016-01-18 12:55:38 DEBUG    SEARCHQUEUE-BACKLOG-77398 :: [Spotweb 2g] :: Search URL: http://website.com/spotweb/api?apikey=**********&tvdbid=77398&season=1&maxage=2600&cat=5030%2C5040&
q=X-Files+S01E01&limit=100&t=tvsearch&offset=0&ep=1
```

Is this sufficient?

**Comment by JBFUK** [comment] 2016-01-20 12:58
I also have this issue.  I have the quality for the show set to 1080p but some old episodes are lower quality.  I have tried setting them to 'Ignored' and/or 'Skipped' which removes them form the backlog list but when i check again the next day the status of the episodes is back to 'Downloaded 720p' or similar and they are back in the backlog queue.  Very annoying and wasting a lots of bandwidth.

Version:	Branch: master
Commit: b6c8acedafc0057f6da5e2f7ca91213c83fe2e42
Version: v5.1.2

**Comment by strike84** [comment] 2016-01-20 14:27
@pven make sure all your files are named correctly. As you can see from your screenshot SR thinks the 2 of the ep's are 199 and 200 which doesn't exist. Also make sure you have only 1 copy of each episode (if you have 2 or more this happens). Also make sure you only have one folder for each season. @JBFUK check your files and folders as well.

**Comment by strike84** [comment] 2016-01-20 14:49
@JBFUK I just reproduced your issue. You said in IRC that you had 2 season folders and I have confirmed that this happens even if there are different episodes in the folders. I created one season 1 folder and one season 01 folder with different episodes in them and they are not set as skipped even if I told SR to. If I manually sets them to skipped/ignored/archived and do a full update of the show they end up as downloaded again.

**Comment by JBFUK** [comment] 2016-01-20 15:05
Great so as a workaround I will rename the season folders, however it seems you have confirmed that there is an underlying issue.

**Comment by strike84** [comment] 2016-01-20 15:40
I don't know if this is something that can be prevented (in the code) or even if the dev's will fix it if they can (you'll have to ask them) it's really a user error imo.

**Comment by JBFUK** [comment] 2016-01-20 15:54
I don't understand where the user error is?  An episode is recognised as being present, its status is set to ignored, it displays as being ignored but it is in-fact not ignored and the status reverts to the old value.  If the folder names were an issue it should not recognise and display the episode in the first place.

**Comment by strike84** [comment] 2016-01-20 16:09
The folder names are not an issue itself, SR accepts both 1 and 01 in the season folder name. The issue is having 2 folders of the same season (that's the user error, imo anyway) then SR gets confused. But ofc it sees the episodes as present if they are there as long as the folder is named something that SR accepts even if there are 2 folders. Exactly what happens in the code and why SR get confused I can not tell you since I'm not a programmer, but SR doesn't like it that's for sure.

**Comment by duramato** [comment] 2016-01-20 16:11
Well it doesnt make much sense having 2 folder for the same season... lol

**Comment by JBFUK** [comment] 2016-01-20 16:15
Agreed it doesn't make much sense.  It's a result of migrating from Sickbeard and the different naming options not quite matching up not an intentional choice.

I'm surprised that there isn't an automated migration path as part of the SR install to switch users over given that most Sickbeard users will be moving to SR (or Sonarr) at some point.

**Comment by duramato** [comment] 2016-01-20 16:16
@JBFUK SickRage is light years away from SickBeard , but it shouldnt be much of a hassle to switch over ( same applies to sonarr, duckietv etc.. )

**Comment by JBFUK** [comment] 2016-01-20 16:17
Yeah on the whole it's been good - this is the only issue I've had so far.

**Comment by pven** [comment] 2016-01-21 08:57
@strike84 : there are no episodes at all on my drive, so renaming is useless and doub le is also no the case. I try to skip the first 9 seasons, but it  keeps on downloading the episodes I don't want.

Is removng and re-adding an option?

**Comment by pven** [comment] 2016-01-22 10:22
Looks like it is working as expected. Was this a blitch in the matrix? ;-)

**Closed** 2016-01-27 07:34 UTC
Labels: Need more info
