### ISSUE TITLE
Episodes being skipped when scanning

### ISSUE THREAD

**Issue by nervling** [SickRage/sickrage-issues#402] opened 2016-01-03 18:04 UTC
I switched from SickRageTV and ended up rescanning my library from scratch, and a lot of things aren't being picked up. I'm running UnRaid, and SickRage is running as root. As far as I can tell, there is no common pattern to the files being skipped. I'm currently running the master branch, at commit 4423fe95002315b812b4ef9867ea6df7d94c2083.

For example I have the following episodes, but only episodes 13 and 14 are picked up.

```
-rw-rw-rw- 1 root   root  2134178965 2015-03-02 04:01 The\ Walking\ Dead\ -\ S05E12\ -\ Remember\ -\ HD\ TV.mkv
-rw-rw-rw- 1 root   root  2221700412 2015-03-09 03:01 The\ Walking\ Dead\ -\ S05E13\ -\ Forget\ -\ HD\ TV.mkv
-rw-rw-rw- 1 root   root        4705 2016-01-03 09:59 The\ Walking\ Dead\ -\ S05E13\ -\ Forget\ -\ HD\ TV.nfo
-rw-rw-rw- 1 root   root       51994 2016-01-03 10:00 The\ Walking\ Dead\ -\ S05E13\ -\ Forget\ -\ HD\ TV-thumb.jpg
-rw-rw-rw- 1 root   root  1891031370 2015-03-16 03:01 The\ Walking\ Dead\ -\ S05E14\ -\ Spend\ -\ HD\ TV.mkv
-rw-rw-rw- 1 root   root        4716 2016-01-03 10:00 The\ Walking\ Dead\ -\ S05E14\ -\ Spend\ -\ HD\ TV.nfo
-rw-rw-rw- 1 root   root       50698 2016-01-03 10:00 The\ Walking\ Dead\ -\ S05E14\ -\ Spend\ -\ HD\ TV-thumb.jpg
```

I enabled debug logs, and sickrage is finding the file. The logs don't contain any other references to the missing episodes though. Full log below as well.

[sickrage.txt](https://github.com/SickRage/sickrage-issues/files/76684/sickrage.txt)

```
2016-01-03 09:55:01 DEBUG    SHOWQUEUE-REFRESH :: 153021: Found files: [u'/mnt/user/media/TV Shows/The Walking Dead/Season 01/The Walking Dead - S01E03 - Tell It to the Frogs - SDTV.avi', u'/mnt/user/media/TV Shows/The Walking Dead/Season 01/The Walking Dead - S01E00 -  - SDTV.avi', u'/mnt/user/media/TV Shows/The Walking Dead/Season 01/The Walking Dead - S01E04 - Vatos - SDTV.avi', u'/mnt/user/media/TV Shows/The Walking Dead/Season 01/The Walking Dead - S01E05 - Wildfire - SDTV.avi', u'/mnt/user/media/TV Shows/The Walking Dead/Season 01/The Walking Dead - S01E01 - Days Gone Bye - SDTV.avi', u'/mnt/user/media/TV Shows/The Walking Dead/Season 01/The Walking Dead - S01E02 - Guts - SDTV.avi', u'/mnt/user/media/TV Shows/The Walking Dead/Season 01/The Walking Dead - S01E06 - TS-19 - SDTV.avi', u'/mnt/user/media/TV Shows/The Walking Dead/Season 02/The Walking Dead - S02E12 - Better Angels - SDTV.avi', u'/mnt/user/media/TV Shows/The Walking Dead/Season 02/The Walking Dead - S02E13 - Beside the Dying Fire - SDTV.avi', u'/mnt/user/media/TV Shows/The Walking Dead/Season 02/The Walking Dead - S02E03 - Save the Last One - SDTV.avi', u'/mnt/user/media/TV Shows/The Walking Dead/Season 02/The Walking Dead - S02E10 - 18 Miles Out - SDTV.avi', u'/mnt/user/media/TV Shows/The Walking Dead/Season 02/The Walking Dead - S02E04 - Cherokee Rose - SDTV.avi', u'/mnt/user/media/TV Shows/The Walking Dead/Season 02/The Walking Dead - S02E11 - Judge, Jury, Executioner - SDTV.avi', u'/mnt/user/media/TV Shows/The Walking Dead/Season 02/The Walking Dead - S02E09 - Triggerfinger - SDTV.avi', u'/mnt/user/media/TV Shows/The Walking Dead/Season 02/The Walking Dead - S02E02 - Bloodletting - SDTV.avi', u'/mnt/user/media/TV Shows/The Walking Dead/Season 02/The Walking Dead - S02E08 - Nebraska - SDTV.avi', u'/mnt/user/media/TV Shows/The Walking Dead/Season 02/The Walking Dead - S02E05 - Chupacabra - SDTV.avi', u'/mnt/user/media/TV Shows/The Walking Dead/Season 02/The Walking Dead - S02E01 - What Lies Ahead - SDTV.avi', u'/mnt/user/media/TV Shows/The Walking Dead/Season 02/The Walking Dead - S02E07 - Pretty Much Dead Already - SDTV.avi', u'/mnt/user/media/TV Shows/The Walking Dead/Season 02/The Walking Dead - S02E06 - Secrets - SDTV.avi', u'/mnt/user/media/TV Shows/The Walking Dead/Season 03/The Walking Dead - S03E13 - Arrow on the Doorpost - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 03/The Walking Dead - S03E14 - Prey - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 03/The Walking Dead - S03E01 - Seed - SDTV.mp4', u'/mnt/user/media/TV Shows/The Walking Dead/Season 03/The Walking Dead - S03E16 - Welcome to the Tombs - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 03/The Walking Dead - S03E06 - Hounded - SDTV.mp4', u'/mnt/user/media/TV Shows/The Walking Dead/Season 03/The Walking Dead - S03E07 - When the Dead Come Knocking - SDTV.mp4', u'/mnt/user/media/TV Shows/The Walking Dead/Season 03/The Walking Dead - S03E15 - This Sorrowful Life - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 03/The Walking Dead - S03E09 - The Suicide King - SDTV.mp4', u'/mnt/user/media/TV Shows/The Walking Dead/Season 03/The Walking Dead - S03E05 - Say the Word - SDTV.mp4', u'/mnt/user/media/TV Shows/The Walking Dead/Season 03/The Walking Dead - S03E10 - Home - SDTV.mp4', u'/mnt/user/media/TV Shows/The Walking Dead/Season 03/The Walking Dead - S03E08 - Made to Suffer - SDTV.mp4', u"/mnt/user/media/TV Shows/The Walking Dead/Season 03/The Walking Dead - S03E11 - I Ain't a Judas - 720p HDTV.mkv", u'/mnt/user/media/TV Shows/The Walking Dead/Season 03/The Walking Dead - S03E02 - Sick - SDTV.mp4', u'/mnt/user/media/TV Shows/The Walking Dead/Season 03/The Walking Dead - S03E04 - Killer Within - SDTV.mp4', u'/mnt/user/media/TV Shows/The Walking Dead/Season 03/The Walking Dead - S03E03 - Walk with Me - SDTV.mp4', u'/mnt/user/media/TV Shows/The Walking Dead/Season 03/The Walking Dead - S03E12 - Clear - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 04/The Walking Dead - S04E01 - 30 Days Without an Accident - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 04/The Walking Dead - S04E16 - A - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 04/The Walking Dead - S04E03 - Isolation - 1080p WEB-DL.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 04/The Walking Dead - S04E02 - Infected - 1080p WEB-DL.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 04/The Walking Dead - S04E08 - Too Far Gone - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 04/The Walking Dead - S04E05 - Internment - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 04/The Walking Dead - S04E07 - Dead Weight - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 04/The Walking Dead - S04E10 - Inmates - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 04/The Walking Dead - S04E04 - Indifference - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 04/The Walking Dead - S04E09 - After - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 04/The Walking Dead - S04E14 - The Grove - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 04/The Walking Dead - S04E13 - Alone - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 04/The Walking Dead - S04E12 - Still - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 04/The Walking Dead - S04E11 - Claimed - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 04/The Walking Dead - S04E06 - Live Bait - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 04/The Walking Dead - S04E15 - Us - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 05/The Walking Dead - S05E04 - Slabtown - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 05/The Walking Dead - S05E08 - Coda - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 05/The Walking Dead - S05E06 - Consumed - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 05/The Walking Dead - S05E10 - Them - HD TV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 05/The Walking Dead - S05E13 - Forget - HD TV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 05/The Walking Dead - S05E11 - The Distance - HD TV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 05/The Walking Dead - S05E05 - Self Help - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 05/The Walking Dead - S05E14 - Spend - HD TV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 05/The Walking Dead - S05E09 - What Happened and What\u2019s Going On - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 05/The Walking Dead - S05E02 - Strangers - 720p WEB-DL.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 05/The Walking Dead - S05E01 - No Sanctuary - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 05/The Walking Dead - S05E15 - Try - 720p WEB-DL.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 05/The Walking Dead - S05E12 - Remember - HD TV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 05/The Walking Dead - S05E03 - Four Walls and a Roof - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 05/The Walking Dead - S05E07 - Crossed - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 06/The Walking Dead - S06E01 - First Time Again - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 06/The Walking Dead - S06E02 - JSS - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 06/The Walking Dead - S06E08 - Start to Finish - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 06/The Walking Dead - S06E03 - Thank You - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 06/The Walking Dead - S06E05 - Now - 720p HDTV.mkv', u'/mnt/user/media/TV Shows/The Walking Dead/Season 06/The Walking Dead - S06E06 - Always Accountable - 720p HDTV.mkv', u"/mnt/user/media/TV Shows/The Walking Dead/Season 06/The Walking Dead - S06E04 - Here's Not Here - 720p HDTV.mkv", u'/mnt/user/media/TV Shows/The Walking Dead/Season 06/The Walking Dead - S06E07 - Heads Up - 720p HDTV.mkv']
```

**Comment by SickRage2** [comment] 2016-01-03 18:04
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)
- [ ] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by labrys** [comment] 2016-01-03 18:09
@nervling Please add all the required information

**Comment by nervling** [comment] 2016-01-03 18:14
@labrys what am I missing? The only thing I see that I didn't add is Python version, which is 2.7.3. I don't know how to repro the issue.

**Comment by labrys** [comment] 2016-01-03 18:17
Python version and unless I missed it earlier commit hash which I see you have now.

**Comment by nervling** [comment] 2016-01-03 18:20
Gotcha, I edited at some point to add it, so probably wasn't there when you looked. Thanks.

**Comment by labrys** [comment] 2016-01-03 18:45
@nervling Per your logs:
```
2016-01-03 09:59:31 DEBUG    SHOWQUEUE-FORCE-UPDATE :: 153021: This episode The Walking Dead - S05E12 has no absolute number on theTVDB
```
The Walking Dead - S05E12 has no absolute number on theTVDB

**Comment by nervling** [comment] 2016-01-03 18:50
Not sure what that means, Is there some setting I need to disable?

**Comment by labrys** [comment] 2016-01-03 19:08
I assume you have Absolute numbering enabled for The Walking Dead.  Absolute numbering means that all episodes are numbered sequentially instead of by season/episode number.

**Comment by nervling** [comment] 2016-01-03 19:19
I don't see anything like that enabled. The only setting I see turned on for the show is Season Folders. Is there a top level setting or something I'm missing? I have anime enabled, but the walking dead isn't marked as an anime.

**Comment by whipcracker** [comment] 2016-01-04 05:35
It shouldn't be marked as "anime". Anime is an example of a TV series that DOES use absolute numbering. I find it easier to think that nearly all popular TV series usually have Seasons and Episode numbers, with the exception of a few...

Go to the TV show - click "Edit" and untick everything, except for "Season Folders" and make sure that all seasons have their own separate folder named "Season 1", "Season 2" etc. It should pick that up once you force a full update :)

**Comment by nervling** [comment] 2016-01-04 05:36
That's what I'm saying, is not marked as anime. It's marked as season
folders and nothing else.

**Comment by whipcracker** [comment] 2016-01-04 05:42
Have you tried deleting the whole TV show and adding as an existing show again? Another option would be to shut down SR and in the SR directory, delete the cache.db folder and in the cache folder, delete the "mako" (if it's there) and the "sessions" folders, then start SR again, then re-add the "existing" show.

**Comment by nervling** [comment] 2016-01-04 05:43
Yes I did delete the show and re-add it. I did not try deleting the cache,
but I can if you think that may help.

**Comment by whipcracker** [comment] 2016-01-04 05:45
I've known a few weird issues to clear after deleting the cache.db file and those two folders (it's usually one of the first steps to sorting out issues in SR) and any further issues I leave for the experts ;)

Just make sure that the files and folders are named correctly and when adding an existing show, it may show the TV show right there and then to re-add back to the TV Show listing.

**Comment by labrys** [comment] 2016-01-04 09:11
@whipcracker Mako and sessions folders don't need to be deleted any more.

**Comment by nervling** [comment] 2016-01-04 15:43
Labrys, any ideas what's wrong then? My configuration seems correct, so
maybe sickrage is trying to lookup an absolute number even though it's
disabled? Can you repro?

**Comment by labrys** [comment] 2016-01-04 21:55
@nervling I would try a clean install, no config, no database... add only the one existing show and see if you can reproduce it.  I have tested it on my end with TWD and it picked everything up clean.  If it works then (which it should) then its a problem with either your config, cache, or database.

**Comment by nervling** [comment] 2016-01-05 03:38
I think I found the issue. Try generating Kodi 12+ metadata when you scan, I think that will repro the error. I changed to Kodi, and it works now.

**Comment by labrys** [comment] 2016-01-05 04:43
@nervling I use KODI 12+.

**Comment by nervling** [comment] 2016-01-05 05:42
Did you try fresh to repro it? As soon as I disabled Kodi 12+ metadata (I had everything but fan art checked) it started working.

**Comment by labrys** [comment] 2016-01-05 05:48
Yes I cloned new copied my config... cleared out existing root directories.. added existing.. everything populated.

**Comment by nervling** [comment] 2016-01-05 05:55
Weird. Well, I think regular kodi works with plex, so this is good enough
for me. Feel free to close if you can't repro.

**Comment by nervling** [comment] 2016-01-05 05:55
Thanks for the numerous quick replies!

**Comment by labrys** [comment] 2016-01-05 06:08
@nervling No problem and yes regular KODI works with plex.

**Closed by labrys** 2016-01-05 06:08 UTC
