### ISSUE TITLE
Constant reloads on any tabbed page when using Chrome

### ISSUE THREAD

**Issue by andrewjennings** [SickRage/sickrage-issues#580] opened 2016-01-21 15:57 UTC
Whenever I'm using the SickRage web interface, loading any page with tabs on it causes Chrome to constantly reload, making the page unusable.

When loading one of these pages, the following message appears in the Chrome Dev Tools console. This message does not appear on other pages.
```Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.```

Some examples of pages where this happens:
/addShows/newShow/
/config/general/
/config/notifications/

This error has happened to me consistently for months in Chrome (currently Version 47.0.2526.111 (64-bit)) on OSX 10.11, Windows 8.1 and Windows 10.  I've tried clearing my browser cache and following the trouble-shooting steps listed on the front page of the sickrage-issues repo.

Current SR version from the "Help and Info" page in my installation. 
Version:	Branch: master
Commit: 66fa37c556784fa3b41a06bb3043bd854d165c10
Version: 2016.01.20-1

I'm running SickRage on Ubuntu 14.04.3, using an https connection.  Please let me know if there's anything else I can do to help you track down this bug.

Here's [a video showing the reloading behavior](https://drive.google.com/file/d/0B1ygQDTd59mGelRTYVJsUHFxdXc/view?usp=sharing).

**Comment by SickRage2** [comment] 2016-01-21 15:57
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment] 2016-01-21 16:18
First what you can try is to shutdown SR, and remove the cache.db file. Then restart SR.

Some other things you can try : 
- For testing change Sickrage to use `http` instead of `1 https`. 
- Try another browser.
- Are you using a proxy or similar.? 

If this `bug` was for every1 i'm sure that the issue tracker would be flooded with reports, as that isnt the case its probbebly caused due to something local/else than Sickrage.

**Comment by andrewjennings** [comment] 2016-01-21 16:53
Thanks for looking into this. I have tried other browsers - only happens in Chrome. But it does happen on every platform.

  * Tried shutting down and deleting cache.db. Still happens to me.  
  * I'm not using a proxy of any kind.
  * I'll try switching from https next.

This bug has been happening to me for months and I'm only just now reporting it now because I'm sick of opening Safari to add new shows.  So it may be happening to more people than you think - most people don't write bug reports.  It's also only on pages w/ tabs so it's something in that part of SickRage's UI.  It's all minimized javascript so I couldn't dig into it and see what was throwing that message in the Dev Tools.

**Comment by medariox** [comment] 2016-01-21 18:02
I use SR with Chrome on a daily basis and never experienced such a problem, only difference is that I don't use https. Could it be that you have some old JS files in your SR install? Maybe try to make a new temporary clone, just to see if that solves it. Anyway, fyi, you can debug minimized JS code in Chrome by pressing the brackets { }:
![debug](https://snapr.pw/i/f4289b7ef6.png)

**Comment by andrewjennings** [comment] 2016-01-21 19:13
Thanks for the tip on debugging minimized JS in Chrome. I had no idea you could do that and it's very handy.

Switching between http and https makes the problem go away for a few minutes. I'm really puzzled.  Here's what I've done:
  * Shut down old sickrage instance and renamed it. Cloned new sickrage repo. Moved config file over and started up. Problem reloading still happens.
  * Shut down sickrage, changed enable_https to 0. Started up. Problem went away!
  * Shut down sickrage, changed enable_https back to 1. Started up. Problem still gone.
  * Shut down sickrage, copy sickbeard.db and sickbeard.db.v42 from old instance over. Delete cache.db. Started up. Problem still gone.
  * Mouse around a bit, enjoy working sickrage install. Five minutes later, the problem is back.
  * Shut down sickrage, changed enable_https to 0. Started up. Problem went away!
  * Shut down sickrage, changed enable_https back to 1. Started up. Problem still gone.
 
I notice that the deprecation warning doesn't appears in the Chrome dev tools when the bug isn't happening.

I'd be happy to do some JS debugging to get at the root of this weirdness. Looks like the [dev environment instructions](https://github.com/SickRage/sickrage-issues/wiki/How-to-setup-a-development-enviroment) need some TLC; they only explain how to add a new js library.  Any tips on how to run using non-minimized js so I can actually make some edits and a pull request?

Thanks for your help.

**Comment by neoatomic** [comment] 2016-01-21 19:23
If it is really Java related than @OmgImAlexis should be able to tell for sure. :P 
Did you try to disable your addons/plugins in Chrome.? Maybe one of those is acting up.

**Comment by OmgImAlexis** [comment] 2016-01-22 08:55
@andrewjennings if you set DEVELOPER=1 in the config.ini you should be loading `core.js` instead of `core.min.js`.
I'd suggest you try see if you can reproduce this in incognito mode or something else that is free of browser extensions that could be causing issues.

The video looks like it may be caused by some of the ajax we're using and could be using http or an incorrect link somewhere that means we get a mako issue and that'll cause a redirect.

**Comment by andrewjennings** [comment] 2016-01-24 20:23
Perfect, @OmgImAlexis. I'll set that option and see if I can track down the issue.Thank you!

**Comment by neoatomic** [comment] 2016-01-29 17:20
@andrewjennings As you haven't reported back, i'm going to assume you haven't found anything, so i will close this for now. If you haven't had the time, and indeed find a bug, just update this issue and will reopen as a bug, and take further steps.

**Closed by neoatomic** 2016-01-29 17:20 UTC

**Comment by andrewjennings** [comment] 2016-02-01 20:21
Thanks. I haven't had time to look into it beyond making it happen in an incognito window w/ no extensions. So it's not an extension but I haven't gotten past that.

**Comment by OmgImAlexis** [comment] 2016-02-02 05:12
Well since no one else is reporting it it's gotta be something on your end otherwise we'd have reports daily about this.

Can you try it on another computer?

**Comment by andrewjennings** [comment] 2016-02-08 16:56
It's an odd one and seems to be a bug in vender.min.js, not core.js

I use a bookmark like https://username:password@server.xyz/  so that I don't have to type in Apache authentication on my little server. It seems that the URL format is what causes the reloading to happen.  If I take out the authentication bits, it works fine.  Makes sense that it's OK in other browsers since I'm not using a bookmark with them.

Where does vender.min.js come from?  It doesn't seem to be a minimized version of anything else in the gui/slick/js folder.

**Comment by OmgImAlexis** [comment] 2016-02-09 05:04
It's a minified version of all of the libraries bower downloads. If you have node, npm, bower and grunt installed you'll be able to run `grunt refresh` in the `.build` directory and it'll rebuild everything.
