### ISSUE TITLE
[APP SUBMITTED]: %d format: a number is required, not NoneType

### ISSUE THREAD

**Issue by Danny89530** [SickRage/sickrage-issues#504] opened 2016-01-15 15:19 UTC
### INFO
Python Version: **2.7.3 (default, Mar 14 2014, 11:57:14) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-686-pae-i686-with-debian-7.9**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@abfff93b766d6b8eb81cb2ca4c410b795f5343e5
No Log available with ERRORS:
### ERROR
```
Thread-62 :: Failed doing webui callback: Traceback (most recent call last):
  File "/opt/sickrage/sickbeard/webserve.py", line 281, in async_call
    result = function(**kwargs)
  File "/opt/sickrage/sickbeard/webserve.py", line 3140, in backlogOverview
    epCats['S%02dE%02d' % (curResult['season'], curResult['episode'])] = curEpCat
TypeError: %d format: a number is required, not NoneType
 [abfff93]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment] 2016-01-15 15:19
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by Danny89530** [comment] 2016-01-15 15:21
Hi,
i got this error message when i try to go to the "Manage -> Backlog Overview"

**Comment by cbrherms** [comment] 2016-01-16 01:21
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.3-RELEASE-p28-amd64-64bit-ELF**
Locale: UTF-8
Branch: **develop**
Commit: SickRage/SickRage@0b1191512f1f6f973b5bc60f4e6d8649ba367700
No Log available with ERRORS:
### ERROR
```
Thread-30 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 281, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 3140, in backlogOverview
    epCats['S%02dE%02d' % (curResult['season'], curResult['episode'])] = curEpCat
TypeError: %d format: a number is required, not NoneType
 [0b11915]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by cbrherms** [comment] 2016-01-16 01:26
same here, tried both master and devel branch to no effect.

**Comment by Falx** [comment] 2016-01-16 09:04
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:33:06) [GCC 4.3.2]**
Operating System: **Linux-2.6.32.12-ppc-with-glibc2.0**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5997b76596ce42b261f041d7daa12dc6934e024e
Link to Log: https://gist.github.com/160a63ffc6ed8d515fa3
### ERROR
```
SHOWQUEUE-REFRESH :: 295068: Could not refresh subtitles [5997b76]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by cbrherms** [comment] 2016-01-16 17:06
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.3-RELEASE-p28-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@5997b76596ce42b261f041d7daa12dc6934e024e
No Log available with ERRORS:
### ERROR
```
Thread-41 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 281, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 3140, in backlogOverview
    epCats['S%02dE%02d' % (curResult['season'], curResult['episode'])] = curEpCat
TypeError: %d format: a number is required, not NoneType
 [5997b76]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by medariox** [comment] 2016-01-17 11:57
Can't reproduce this. What did you do to get this error?

**Comment by fernandog** [comment] 2016-01-17 12:03
@medariox using phone but IMO:

 "epCats['S%02dE%02d' % (curResult['season'] or 0, curResult['episode']) or 0] = curEpCat

**Comment by medariox** [comment] 2016-01-17 12:13
@fernandog 
Probably yes. Still wanted to try to reproduce it tho.

**Comment by fernandog** [comment] 2016-01-17 12:17
I think it's an anime with absolute number enabled

**Comment by miigotu** [comment] 2016-01-17 18:59
Open every show until you find which one it is.

**Comment by cbrherms** [comment] 2016-01-19 02:41
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.1-RELEASE-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@b6c8acedafc0057f6da5e2f7ca91213c83fe2e42
No Log available with ERRORS:
### ERROR
```
Thread-39 :: Failed doing webui callback: Traceback (most recent call last):
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 281, in async_call
    result = function(**kwargs)
  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/webserve.py", line 3140, in backlogOverview
    epCats['S%02dE%02d' % (curResult['season'], curResult['episode'])] = curEpCat
TypeError: %d format: a number is required, not NoneType
 [af9a7fd]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by veribaka** [comment] 2016-01-19 10:49
### INFO
Python Version: **2.7.9 (default, Mar  1 2015, 13:48:22) [GCC 4.9.2]**
Operating System: **Linux-4.2.3-sunxi-armv7l-with-debian-8.2**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@b6c8acedafc0057f6da5e2f7ca91213c83fe2e42
Link to Log: https://gist.github.com/56a09b227237c48cd67b
### ERROR
```
FINDSUBTITLES :: Exception generated in thread FINDSUBTITLES: %d format: a number is required, not NoneType [b6c8ace]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by fernandog** [comment] 2016-01-19 11:05
@medariox ^^

**Comment by medariox** [comment] 2016-01-19 11:13
@fernandog 
Problem needs to be fixed in webserve.py

**Comment by fernandog** [comment] 2016-01-19 11:18
so we wait then a better fix than mine
this fix needs to check if is anime and/or absolute.
problem is: it crashes the thread and it doesn't continue.

**Comment by Danny89530** [comment] 2016-01-19 17:25
Hi,
I've opened every show (as suggested by @miigotu ) and I've no errors.
The error cames when I open "Backlog Overview" from "Manage". It happens everywhere (home, show page, settings page).
I have no anime in my library and every show is 'Scene numbered'.

**Comment by fernandog** [comment] 2016-01-19 17:33
@Danny89530 how many snatched episodes do you have?

if is not much, open show page of those snatched episodes, click "select columns" button, click to show "Scene" and "Scene Absolute" columns

check if there is a empty value in those columns for any of those shows

**Comment by Danny89530** [comment] 2016-01-19 17:37
Like this?
<img width="304" alt="schermata 2016-01-19 alle 18 36 36" src="https://cloud.githubusercontent.com/assets/3729455/12426749/a0eb1bea-bedb-11e5-8b0e-357151455c88.PNG">

**Comment by fernandog** [comment] 2016-01-19 17:38
do you have team viewer?  if you do, join #sickrage-issues please and PM me

**Comment by Danny89530** [comment] 2016-01-19 18:18
So,
I've found three shows, setting them to "pause", the backlog page opens correctly.
The filename of every episode of the shows is "ShowName - 3x01 - EpTitle.ext".
I've configured these three shows as "Anime" and "Scene Numbered" (when i've installed SickRage, long time ago and never had this problem before).
When i open the Show page i get this error:

<img width="723" alt="schermata 2016-01-19 alle 19 14 06" src="https://cloud.githubusercontent.com/assets/3729455/12427667/d693b78e-bee0-11e5-9269-bff110d8c317.PNG">

I've modified the shows removing "Scene numbering" and "Anime" flags with no effect.

**Comment by Danny89530** [comment] 2016-01-19 18:26
This is the TVDB page of one of them:
http://thetvdb.com/?tab=season&seriesid=76666&seasonid=11061&lid=15

**Comment by miigotu** [comment] 2016-01-19 19:51
You would disable scene numbering and force a full update on the show.

**Comment by fernandog** [comment] 2016-01-20 11:08
@Danny89530 can you join IRC?

**Comment by fernandog** [comment] 2016-01-21 11:05
@Danny89530 around ?

**Comment by megabitus98** [comment] 2016-01-23 13:11
### INFO
Python Version: **2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.10586**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@f67f6e90fc71e6e5ad30a264b3ce4aea68f8e23f
No Log available with ERRORS:
### ERROR
```
Thread-41 :: Failed doing webui callback: Traceback (most recent call last):
  File "J:\SickRage\sickbeard\webserve.py", line 281, in async_call
    result = function(**kwargs)
  File "J:\SickRage\sickbeard\webserve.py", line 3140, in backlogOverview
    epCats['S%02dE%02d' % (curResult['season'], curResult['episode'])] = curEpCat
TypeError: %d format: a number is required, not NoneType
 [f67f6e9]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by yongbi85** [comment] 2016-01-23 22:42
### INFO
Python Version: **2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]**
Operating System: **Linux-3.10.35-x86_64-with-glibc2.2.5**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@f67f6e90fc71e6e5ad30a264b3ce4aea68f8e23f
No Log available with ERRORS:
### ERROR
```
Thread-18 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 281, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 3140, in backlogOverview
    epCats['S%02dE%02d' % (curResult['season'], curResult['episode'])] = curEpCat
TypeError: %d format: a number is required, not NoneType
 [f67f6e9]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by yongbi85** [comment] 2016-01-23 22:49
I have this issue in Backlog overview but I have animes. Those animes are actually also giving me an error when trying to access to them (Mako Error) ; File /usr/local/sickrage/var/SickRage/gui/slick/views/displayShow.mako:56, in render_content:
        % if int(seasonResults[-1]["season"]) == 0:
TypeError: int() argument must be a string or a number, not 'NoneType'

I've tryed to remove them and readd them but still the same issue...
Several animes are touched and I guess this is the reason i get this bug in Backlog oveview.
Animes : Fairy Tail, Naruto Shippuden and some more.

**Closed** 2016-01-24 05:35 UTC
Labels: Bug/Issue, Fixed

**Comment by Demogorg0N** [comment] 2016-01-31 19:26
### INFO
Python Version: **2.7.9 (default, Sep  9 2015, 14:50:03) [GCC 4.2.1 20070831 patched [FreeBSD]]**
Operating System: **FreeBSD-9.3-RELEASE-p31-amd64-64bit-ELF**
Locale: UTF-8
Branch: **master**
Commit: SickRage/SickRage@f568d1515557f854042511d7bfee3ae070c864bd
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-ADD :: Error searching dir for episodes: %d format: a number is required, not NoneType [f568d15]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by Riceak** [comment] 2016-03-10 13:51
### INFO
Python Version: **2.7.11rc1 (v2.7.11rc1:82dd9545bd93, Nov 21 2015, 23:25:27) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-7-6.1.7601-SP1**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@99a6af8382a36339a55431308fad5ca991ad5d1a
No Log available with ERRORS:
### ERROR
```
POSTPROCESSER :: [99a6af8] Exception generated in thread POSTPROCESSER: %d format: a number is required, not NoneType
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
