### ISSUE TITLE
Blank pages after update

### ISSUE THREAD

**Issue by Flabadab** [SickRage/sickrage-issues#1104] opened 2016-03-07 05:20 UTC
Hi There,

SickRage was working great until last night, when I updated and now I just get white pages.
I've tried re-installing from scratch, same thing. Please see error below.

Branch/Commit: Master 
OS: Windows 10
What you did: Updated to latest version as at 06 Mar 2016
What happened: White pages when trying to access SickRage url
What you expected: The home page
Logs:
```
2016-03-07 07:15:04 INFO     MAIN :: Starting SickRage [master] using 'C:\SickRage\config.ini'
2016-03-07 07:15:04 INFO     MAIN :: New API generated
2016-03-07 07:15:04 INFO     TORNADO :: Starting SickRage on http://0.0.0.0:8081/
2016-03-07 07:15:04 INFO     CHECKVERSION :: Checking for updates using GIT
2016-03-07 07:15:06 ERROR    Thread-19 :: [19934e3] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 714, in index
    return t.render(title="Home", header="Show List", topmenu="home", showlists=showlists, show_stat=stats[0], max_download_count=stats[1], controller="home", action="index")
  File "C:\SickRage\sickbeard\webserve.py", line 177, in render
    return get_lookup().get_template('500.mako').render_unicode(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 454, in render_unicode
    as_unicode=True)
  File "C:\SickRage\lib\mako\runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "C:\SickRage\lib\mako\runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "C:\SickRage\lib\mako\runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "C:\SickRage\cache\mako\layouts\main.mako.py", line 489, in render_body
    __M_writer(unicode(datetime.datetime.now(network_timezones.sb_timezone).strftime(sickbeard.DATE_PRESET+" "+sickbeard.TIME_PRESET)))
ValueError: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439
Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 714, in index
    return t.render(title="Home", header="Show List", topmenu="home", showlists=showlists, show_stat=stats[0], max_download_count=stats[1], controller="home", action="index")
  File "C:\SickRage\sickbeard\webserve.py", line 177, in render
    return get_lookup().get_template('500.mako').render_unicode(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 454, in render_unicode
    as_unicode=True)
  File "C:\SickRage\lib\mako\runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "C:\SickRage\lib\mako\runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "C:\SickRage\lib\mako\runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "C:\SickRage\cache\mako\layouts\main.mako.py", line 489, in render_body
    __M_writer(unicode(datetime.datetime.now(network_timezones.sb_timezone).strftime(sickbeard.DATE_PRESET+" "+sickbeard.TIME_PRESET)))
ValueError: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439
2016-03-07 07:15:06 ERROR    Uncaught exception in write_error
Traceback (most recent call last):
  File "C:\SickRage\lib\tornado\web.py", line 976, in send_error
    self.write_error(status_code, **kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 200, in write_error
    return self.finish(t.render(title='404', header='Oops'))
  File "C:\SickRage\sickbeard\webserve.py", line 177, in render
    return get_lookup().get_template('500.mako').render_unicode(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 454, in render_unicode
    as_unicode=True)
  File "C:\SickRage\lib\mako\runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "C:\SickRage\lib\mako\runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "C:\SickRage\lib\mako\runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "C:\SickRage\cache\mako\layouts\main.mako.py", line 489, in render_body
    __M_writer(unicode(datetime.datetime.now(network_timezones.sb_timezone).strftime(sickbeard.DATE_PRESET+" "+sickbeard.TIME_PRESET)))
ValueError: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439
2016-03-07 07:15:11 INFO     MAIN :: [19934e3] Signal 2 caught, saving and exiting...
2016-03-07 07:15:11 INFO     EVENT-QUEUE :: [19934e3] Aborting all threads
2016-03-07 07:15:11 INFO     EVENT-QUEUE :: [19934e3] Waiting for the DAILYSEARCHER thread to exit
2016-03-07 07:15:11 INFO     EVENT-QUEUE :: [19934e3] Waiting for the BACKLOG thread to exit
2016-03-07 07:15:11 INFO     EVENT-QUEUE :: [19934e3] Waiting for the SHOWUPDATER thread to exit
2016-03-07 07:15:11 INFO     EVENT-QUEUE :: [19934e3] Waiting for the CHECKVERSION thread to exit

```

**Comment by SickRage2** [comment] 2016-03-07 05:20
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment] 2016-03-07 07:42
This was fixed a few hours ago. Simply update (git pull) and restart SR

**Comment by Flabadab** [comment] 2016-03-09 15:42
@miigotu 

Thanks. I only got round to trying this today.

I did a pull, but I'm still getting the same error:

```
2016-03-09 17:39:13 INFO     MAIN :: Starting SickRage [master] using 'C:\SickRage\config.ini'
2016-03-09 17:39:13 INFO     MAIN :: New API generated
2016-03-09 17:39:13 INFO     TORNADO :: Starting SickRage on http://0.0.0.0:8081/
2016-03-09 17:39:13 INFO     CHECKVERSION :: Checking for updates using GIT
2016-03-09 17:39:15 ERROR    Thread-19 :: [9149089] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 714, in index
    return t.render(title="Home", header="Show List", topmenu="home", showlists=showlists, show_stat=stats[0], max_download_count=stats[1], controller="home", action="index")
  File "C:\SickRage\sickbeard\webserve.py", line 177, in render
    return get_lookup().get_template('500.mako').render_unicode(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 454, in render_unicode
    as_unicode=True)
  File "C:\SickRage\lib\mako\runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "C:\SickRage\lib\mako\runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "C:\SickRage\lib\mako\runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "C:\SickRage\cache\mako\layouts\main.mako.py", line 489, in render_body
    __M_writer(unicode(datetime.datetime.now(network_timezones.sb_timezone).strftime(sickbeard.DATE_PRESET+" "+sickbeard.TIME_PRESET)))
ValueError: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439
Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 714, in index
    return t.render(title="Home", header="Show List", topmenu="home", showlists=showlists, show_stat=stats[0], max_download_count=stats[1], controller="home", action="index")
  File "C:\SickRage\sickbeard\webserve.py", line 177, in render
    return get_lookup().get_template('500.mako').render_unicode(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 454, in render_unicode
    as_unicode=True)
  File "C:\SickRage\lib\mako\runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "C:\SickRage\lib\mako\runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "C:\SickRage\lib\mako\runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "C:\SickRage\cache\mako\layouts\main.mako.py", line 489, in render_body
    __M_writer(unicode(datetime.datetime.now(network_timezones.sb_timezone).strftime(sickbeard.DATE_PRESET+" "+sickbeard.TIME_PRESET)))
ValueError: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439
2016-03-09 17:39:15 ERROR    Uncaught exception in write_error
Traceback (most recent call last):
  File "C:\SickRage\lib\tornado\web.py", line 976, in send_error
    self.write_error(status_code, **kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 200, in write_error
    return self.finish(t.render(title='404', header='Oops'))
  File "C:\SickRage\sickbeard\webserve.py", line 177, in render
    return get_lookup().get_template('500.mako').render_unicode(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 454, in render_unicode
    as_unicode=True)
  File "C:\SickRage\lib\mako\runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "C:\SickRage\lib\mako\runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "C:\SickRage\lib\mako\runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "C:\SickRage\cache\mako\layouts\main.mako.py", line 489, in render_body
    __M_writer(unicode(datetime.datetime.now(network_timezones.sb_timezone).strftime(sickbeard.DATE_PRESET+" "+sickbeard.TIME_PRESET)))
ValueError: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439
```

**Comment by miigotu** [comment] 2016-03-09 16:18
Could you please try the https://github.com/SickRage/SickRage/tree/dateutil branch?

**Comment by Flabadab** [comment] 2016-03-10 06:37
@miigotu, I see you merged that branch into the develop branch, so I've done a `git checkout develop`, but I'm still getting the same error, although it seems to be at a different point:

```
2016-03-10 08:34:42 INFO     MAIN :: Starting SickRage [develop] using 'C:\SickRage\config.ini'
2016-03-10 08:34:42 INFO     MAIN :: New API generated
2016-03-10 08:34:42 INFO     TORNADO :: Starting SickRage on http://0.0.0.0:8081/
2016-03-10 08:34:42 INFO     CHECKVERSION :: Checking for updates using GIT
2016-03-10 08:34:44 ERROR    Thread-19 :: [e5e9ff8] Failed doing webui callback: Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 714, in index
    return t.render(title="Home", header="Show List", topmenu="home", showlists=showlists, show_stat=stats[0], max_download_count=stats[1], controller="home", action="index")
  File "C:\SickRage\sickbeard\webserve.py", line 177, in render
    return get_lookup().get_template('500.mako').render_unicode(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 454, in render_unicode
    as_unicode=True)
  File "C:\SickRage\lib\mako\runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "C:\SickRage\lib\mako\runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "C:\SickRage\lib\mako\runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "C:\SickRage\cache\mako\layouts\main.mako.py", line 537, in render_body
    __M_writer(unicode(datetime.datetime.now(network_timezones.sb_timezone).strftime(sickbeard.DATE_PRESET+" "+sickbeard.TIME_PRESET)))
ValueError: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439
Traceback (most recent call last):
  File "C:\SickRage\sickbeard\webserve.py", line 287, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 714, in index
    return t.render(title="Home", header="Show List", topmenu="home", showlists=showlists, show_stat=stats[0], max_download_count=stats[1], controller="home", action="index")
  File "C:\SickRage\sickbeard\webserve.py", line 177, in render
    return get_lookup().get_template('500.mako').render_unicode(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 454, in render_unicode
    as_unicode=True)
  File "C:\SickRage\lib\mako\runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "C:\SickRage\lib\mako\runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "C:\SickRage\lib\mako\runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "C:\SickRage\cache\mako\layouts\main.mako.py", line 537, in render_body
    __M_writer(unicode(datetime.datetime.now(network_timezones.sb_timezone).strftime(sickbeard.DATE_PRESET+" "+sickbeard.TIME_PRESET)))
ValueError: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439
2016-03-10 08:34:44 ERROR    Uncaught exception in write_error
Traceback (most recent call last):
  File "C:\SickRage\lib\tornado\web.py", line 976, in send_error
    self.write_error(status_code, **kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 200, in write_error
    return self.finish(t.render(title='404', header='Oops'))
  File "C:\SickRage\sickbeard\webserve.py", line 177, in render
    return get_lookup().get_template('500.mako').render_unicode(*args, **kwargs)
  File "C:\SickRage\lib\mako\template.py", line 454, in render_unicode
    as_unicode=True)
  File "C:\SickRage\lib\mako\runtime.py", line 829, in _render
    **_kwargs_for_callable(callable_, data))
  File "C:\SickRage\lib\mako\runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "C:\SickRage\lib\mako\runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "C:\SickRage\cache\mako\layouts\main.mako.py", line 537, in render_body
    __M_writer(unicode(datetime.datetime.now(network_timezones.sb_timezone).strftime(sickbeard.DATE_PRESET+" "+sickbeard.TIME_PRESET)))
ValueError: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439
```

**Comment by neoatomic** [comment] 2016-03-10 15:19
Could you try to change the (windows) time to another, and see if it then works.? That might help to narrow down the issue.

**Comment by Flabadab** [comment] 2016-03-10 17:20
@neoatomic Thanks for the suggestion. I set my windows time to from UTC+2 (Harare, Pretoria) to UTC Coordinated Universal Time and it appears to be working.

**Comment by neoatomic** [comment] 2016-03-10 17:31
@Flabadab If you are able/want then you could checkout the develop branch. It should be fixed there.

**Comment by miigotu** [comment] 2016-03-11 02:49
@pganssle still some issues with tzwinlocal, any ideas?

**Comment by pganssle** [comment] 2016-03-11 15:11
@miigotu Are you able to reproduce this? I spun up a Windows instance and set the time zone to Harare,  Pretoria and didn't get any kind of issue. I suspect that somewhere you're pulling in the wrong version. Maybe check the reporter's PYTHONPATH.

MWE:

```python
>>> from dateutil.tz import tzutc
>>> from dateutil.tzwin import tzwinlocal
>>> from datetime import datetime
>>> dt = datetime(2016, 3, 1, 5, 15, tzinfo=tzwinlocal())
>>> dt.tzname()
'South Africa Standard Time'
>>> dt.utcoffset()
datetime.timedelta(0, 7200)
>>> dt.strftime('%Y-%m-%d %H:%M%S %z')
'2016-03-01 05:1500 +0200'
>>> dt.astimezone(tzutc())
datetime.datetime(2016, 3, 1, 3, 15, tzinfo=tzutc())
```

Identical results for me with Python 2.7 and 3.4.

**Comment by miigotu** [comment] 2016-03-11 16:00
Im almost positive the wrong version isnt being used (we provide it in lib/ and sys.path.insert lib/)

Maybe this was with the wrong version of SR or w/e, who knows. But until/unless this is still happening after my release last night, closing for now.

OP: Let me know if its still happening on last release.

**Closed by miigotu** 2016-03-11 16:00 UTC
Labels: Need more info
