### ISSUE TITLE
Sometimes better quality downloads doesn't replace previous download

### ISSUE THREAD

**Issue by Quiptix** [SickRage/sickrage-issues#185] opened 2015-12-08 22:25 UTC
SR Version:	BRANCH: (master) / COMMIT: (81aa99c0b4bd39fbf333decd6e4f6c155d9401ef) 
Python Version:	2.7.10 (default, Jul 8 2015, 08:04:18) [GCC 4.3.6]
QNAP NAS

Example:
First downloaded: Season 01/[EPISODE].S01E10.720p.HDTV.X264-DIMENSION.mkv	1009.94 MB
The second download of the same episode: [EPISODE] S01E10 1080p WEB-DL DD5 1 H 264-Coo7 1.88 GB

2nd download is bigger and better quality however:
nzbToSickBeard: [10:58:18] [POSTPROCESS]::SICKBEARD: File exists and new file is the same or lower quality than existing, marking it unsafe to replace

```
2015-12-08 10:58:16 INFO     Thread-40 :: PostProcessing Path: /share/MD0_DATA/Download/******/dst/tv
2015-12-08 10:58:17 INFO     Thread-40 :: Processing /share/MD0_DATA/Download/******/dst/tv/[EPISODE].S01E10.1080p.WEB-DL.DD5.1.H.264-Coo7/[EPISODE].S01E10.[EPNAME].1080p.WEB-DL.DD5.1.H.264-Coo7.mkv ([EPISODE].S01E10.1080p.WEB-DL.DD5.1.H.264-Coo7)
2015-12-08 10:58:17 INFO     Thread-40 :: File exists and new file is the same or lower quality than existing, marking it unsafe to replace
2015-12-08 10:58:17 WARNING  Thread-40 :: Processing failed for /share/MD0_DATA/Download/******/dst/tv/[EPISODE].S01E10.1080p.WEB-DL.DD5.1.H.264-Coo7/[EPISODE].S01E10.[EPNAME].1080p.WEB-DL.DD5.1.H.264-Coo7.mkv:
2015-12-08 10:58:17 WARNING  Thread-40 :: Problem(s) during processing, failed the following files/folders:
2015-12-08 10:58:17 WARNING  Thread-40 :: [/share/MD0_DATA/Download/******/dst/tv/[EPISODE].S01E10.1080p.WEB-DL.DD5.1.H.264-Coo7/[EPISODE].S01E10.[EPNAME].1080p.WEB-DL.DD5.1.H.264-Coo7.mkv : Processing failed: ]
```

Why isn't it overwritten?

**Comment by miigotu** [comment] 2015-12-08 22:51
I assume 720p HDTV is in your preferred list. Those never get replaced.

**Comment by Quiptix** [comment] 2015-12-08 23:26
No, 720p HDTV, 720p WEB-DL and 1080p WEB-DL are allowed and 1080p WEB-DL is the only preferred.
But why get 720p HDTV never replaced?

**Comment by unZane** [comment] 2015-12-09 00:05
I have the same issue:
![allowed-preferred](https://cloud.githubusercontent.com/assets/6288538/11672414/b0bc6146-9e10-11e5-9ba9-a058c0e7edaa.png) 
Auto post processing does not work
```
2015-12-09 00:34:13 WARNING  Thread-40 :: [/mnt/media/downloads/process/tv/*******.S03E08.720p.BluRay/*******.s03e08.720p.bluray.x264-reward.mkv : Processing failed: ]
2015-12-09 00:34:13 WARNING  Thread-40 :: Problem(s) during processing, failed the following files/folders:  
2015-12-09 00:34:13 WARNING  Thread-40 :: Processing failed for /mnt/media/downloads/process/tv/*******.S03E08.720p.BluRay/*******.s03e08.720p.bluray.x264-reward.mkv: 
2015-12-09 00:34:13 INFO     Thread-40 :: File exists and new file is the same or lower quality than existing, marking it unsafe to replace
2015-12-09 00:34:13 INFO     Thread-40 :: Processing /mnt/media/downloads/process/tv/*******.S03E08.720p.BluRay/*******.s03e08.720p.bluray.x264-reward.mkv (*******.S03E08.720p.BluRay.X264-REWARD)
2015-12-09 00:34:12 INFO     Thread-40 :: PostProcessing Path: /mnt/media/downloads/process/tv
```
But manual post processing works with same file and folders
```
2015-12-09 00:39:34 INFO     Thread-59 :: Processing completed
2015-12-09 00:39:34 INFO     Thread-59 :: Processing succeeded for /mnt/media/downloads/process/tv/*******.S03E08.720p.BluRay/*******.s03e08.720p.bluray.x264-reward.mkv
2015-12-09 00:39:29 INFO     Thread-59 :: Release name (*******.s03e08.720p.bluray.x264-reward) found from file (*******.s03e08.720p.bluray.x264-reward.nfo)
2015-12-09 00:39:29 INFO     Thread-59 :: Trying to clean any empty folders under /mnt/media/videos/tvshows/*******/Season 3
2015-12-09 00:39:29 INFO     Thread-59 :: This download is marked a priority download so I'm going to replace an existing file if I find one
2015-12-09 00:39:29 INFO     Thread-59 :: Processing /mnt/media/downloads/process/tv/*******.S03E08.720p.BluRay/*******.s03e08.720p.bluray.x264-reward.mkv (None)
2015-12-09 00:39:28 INFO     Thread-59 :: PostProcessing Path: /mnt/media/downloads/process/tv
```

**Comment by Koal4** [comment] 2015-12-10 06:57
I addressed this issue as well a couple of weeks ago but let it go for the moment (https://github.com/SickRage/sickrage-issues/issues/8#issuecomment-160422873) . But like these guys I'm also still experiencing this problem and pretty sure this is a bug.

Quality settings
Allowed: 720p HDTV, 1080 HDTV, 720p WEB, 1080 WEB
Preferred: 1080 HDTV, 1080P Web

This scenario:
Fargo.S02E09.720p.HDTV.x264-0SEC  release was downloaded and was approxiametly 900mb in size

Preferred filter kicked in and downloaded
Fargo.S02E09.Castle.1080p.WEB-DL.DD5.1.H264-DRACULA which is actually 2GB in size. 

So in above situation the SR did his job by grabbing the new better version but post processing screw things up by thinking the old release was better hence '[POSTPROCESS]::SICKBEARD: File exists and new file is the same or lower quality than existing, marking it unsafe to replace' 


````
INFO	Tue Dec 08 2015 13:33:40	Collection Fargo.S02E09.Castle.1080p.WEB-DL.DD5.1.H264-DRACULA added to history
DETAIL	Tue Dec 08 2015 13:33:40	Deleting file f2edd10b8149f502b21248607dcacba1.vol127+74.par2 from download queue
DETAIL	Tue Dec 08 2015 13:33:40	Deleting file f2edd10b8149f502b21248607dcacba1.vol063+64.par2 from download queue
DETAIL	Tue Dec 08 2015 13:33:40	Deleting file f2edd10b8149f502b21248607dcacba1.vol031+32.par2 from download queue
DETAIL	Tue Dec 08 2015 13:33:40	Deleting file f2edd10b8149f502b21248607dcacba1.vol015+16.par2 from download queue
DETAIL	Tue Dec 08 2015 13:33:40	Deleting file f2edd10b8149f502b21248607dcacba1.vol007+08.par2 from download queue
DETAIL	Tue Dec 08 2015 13:33:40	Deleting file f2edd10b8149f502b21248607dcacba1.vol003+04.par2 from download queue
DETAIL	Tue Dec 08 2015 13:33:40	Deleting file f2edd10b8149f502b21248607dcacba1.vol001+02.par2 from download queue
DETAIL	Tue Dec 08 2015 13:33:40	Deleting file f2edd10b8149f502b21248607dcacba1.vol000+01.par2 from download queue
INFO	Tue Dec 08 2015 13:33:40	Cleaning up download queue for Fargo.S02E09.Castle.1080p.WEB-DL.DD5.1.H264-DRACULA
ERROR	Tue Dec 08 2015 13:33:40	Post-process-script nzbToMedia/nzbToSickBeard.py for Fargo.S02E09.Castle.1080p.WEB-DL.DD5.1.H264-DRACULA failed
INFO	Tue Dec 08 2015 13:33:40	nzbToSickBeard: SickBeard: Failed to post-process - Returned log from SickBeard was not as expected.!
INFO	Tue Dec 08 2015 13:33:40	nzbToSickBeard: [13:33:40] [ERROR]::MAIN: A problem was reported in the /volume1/@appstore/NzbScripts/nzbToMedia/nzbToSickBeard.py script.
INFO	Tue Dec 08 2015 13:33:40	nzbToSickBeard: [13:33:40] [POSTPROCESS]::SICKBEARD: [/volume1/Storage/Downloads/TV/Fargo.S02E09.Castle.1080p.WEB-DL.DD5.1.H264-DRACULA/Fargo.S02E09.Castle.1080p.WEB-DL.DD5.1.H264-DRACULA.mkv : Processing failed: ]
INFO	Tue Dec 08 2015 13:33:40	nzbToSickBeard: [13:33:40] [POSTPROCESS]::SICKBEARD: Problem(s) during processing, failed the following files/folders:
INFO	Tue Dec 08 2015 13:33:40	nzbToSickBeard: [13:33:40] [POSTPROCESS]::SICKBEARD: Processing failed for /volume1/Storage/Downloads/TV/Fargo.S02E09.Castle.1080p.WEB-DL.DD5.1.H264-DRACULA/Fargo.S02E09.Castle.1080p.WEB-DL.DD5.1.H264-DRACULA.mkv:
INFO	Tue Dec 08 2015 13:33:40	nzbToSickBeard: [13:33:40] [POSTPROCESS]::SICKBEARD: File exists and new file is the same or lower quality than existing, marking it unsafe to replace
INFO	Tue Dec 08 2015 13:33:40	nzbToSickBeard: [13:33:40] [POSTPROCESS]::SICKBEARD: File /volume2/Tv-Shows/Fargo/Season 02/Fargo.S02E09.720p.HDTV.x264-0SEC.mkv is smaller than /volume1/Storage/Downloads/TV/Fargo.S02E09.Castle.1080p.WEB-DL.DD5.1.H264-DRACULA/Fargo.S02E09.Castle.1080p.WEB-DL.DD5.1.H264-DRACULA.mkv
INFO	Tue Dec 08 2015 13:33:40	nzbToSickBeard: [13:33:40] [POSTPROCESS]::SICKBEARD: Snatch history had a version in it, using that: v-1
INFO	Tue Dec 08 2015 13:33:40	nzbToSickBeard: [13:33:40] [POSTPROCESS]::SICKBEARD: Is ep a priority download: False
INFO	Tue Dec 08 2015 13:33:40	nzbToSickBeard: [13:33:40] [POSTPROCESS]::SICKBEARD: Snatch history had a quality in it, using that: 1080p WEB-DL
INFO	Tue Dec 08 2015 13:33:40	nzbToSickBeard: [13:33:40] [POSTPROCESS]::SICKBEARD: Retrieving episode object for 2x9
INFO	Tue Dec 08 2015 13:33:40	nzbToSickBeard: [13:33:40] [POSTPROCESS]::SICKBEARD: Found result in history: ('indexerid: 269613\nindexer: 1\nname: Fargo\nlocation: /volume2/Tv-Shows/Fargo\nnetwork: FX (US)\nairs: Monday 10:00 PM\nstatus: Continuing\nstartyear: 2014\ngenre: |Crime|Drama|Thriller|\nclassification: Scripted\nruntime: 45\nquality: 5242996\nscene: False\nsports: False\nanime: False\n', 2, [], 64, -1)
INFO	Tue Dec 08 2015 13:33:40	nzbToSickBeard: [13:33:40] [POSTPROCESS]::SICKBEARD: Processing /volume1/Storage/Downloads/TV/Fargo.S02E09.Castle.1080p.WEB-DL.DD5.1.H264-DRACULA/Fargo.S02E09.Castle.1080p.WEB-DL.DD5.1.H264-DRACULA.mkv (Fargo.S02E09.Castle.1080p.WEB-DL.DD5.1.H264-DRACULA)
INFO	Tue Dec 08 2015 13:33:40	nzbToSickBeard: [13:33:40] [POSTPROCESS]::SICKBEARD: Found unwanted files: ['13803264.txt']
INFO	Tue Dec 08 2015 13:33:40	nzbToSickBeard: [13:33:40] [POSTPROCESS]::SICKBEARD: Processing folder /volume1/Storage/Downloads/TV/Fargo.S02E09.Castle.1080p.WEB-DL.DD5.1.H264-DRACULA
INFO	Tue Dec 08 2015 13:33:40	nzbToSickBeard: [13:33:40] [POSTPROCESS]::SICKBEARD: Processing folder Fargo.S02E09.Castle.1080p.WEB-DL.DD5.1.H264-DRACULA
INFO	Tue Dec 08 2015 13:33:40	nzbToSickBeard: [13:33:40] [POSTPROCESS]::SICKBEARD: PostProcessing VideoInRar: []
INFO	Tue Dec 08 2015 13:33:40	nzbToSickBeard: [13:33:40] [POSTPROCESS]::SICKBEARD: PostProcessing RarContent: []
INFO	Tue Dec 08 2015 13:33:40	nzbToSickBeard: [13:33:40] [POSTPROCESS]::SICKBEARD: PostProcessing VideoFiles: []
INFO	Tue Dec 08 2015 13:33:40	nzbToSickBeard: [13:33:40] [POSTPROCESS]::SICKBEARD: PostProcessing Files: []
INFO	Tue Dec 08 2015 13:33:40	nzbToSickBeard: [13:33:40] [POSTPROCESS]::SICKBEARD: PostProcessing Dirs: [u'Fargo.S02E09.Castle.1080p.WEB-DL.DD5.1.H264-DRACULA']
INFO	Tue Dec 08 2015 13:33:40	nzbToSickBeard: [13:33:40] [POSTPROCESS]::SICKBEARD: PostProcessing Path: /volume1/Storage/Downloads/TV
INFO	Tue Dec 08 2015 13:33:40	nzbToSickBeard: [13:33:40] [POSTPROCESS]::SICKBEARD: TV_DOWNLOAD_DIR:
INFO	Tue Dec 08 2015 13:33:40	nzbToSickBeard: [13:33:40] [POSTPROCESS]::SICKBEARD: Processing folder /volume1/Storage/Downloads/TV/Fargo.S02E09.Castle.1080p.WEB-DL.DD5.1.H264-DRACULA
INFO	Tue Dec 08 2015 13:33:38	nzbToSickBeard: [13:33:38] [POSTPROCESS]::SICKBEARD: SUCCESS: The download succeeded, sending a post-process request
INFO	Tue Dec 08 2015 13:33:38	nzbToSickBeard: [13:33:38] [INFO]::MAIN: FLATTEN: Flattening directory: /volume1/Storage/Downloads/TV/Fargo.S02E09.Castle.1080p.WEB-DL.DD5.1.H264-DRACULA
INFO	Tue Dec 08 2015 13:33:38	nzbToSickBeard: [13:33:38] [INFO]::MAIN: SickBeard:TV fork set to sickrage
INFO	Tue Dec 08 2015 13:33:38	nzbToSickBeard: [13:33:38] [INFO]::MAIN: SickBeard:TV fork auto-detection successful ...
INFO	Tue Dec 08 2015 13:33:38	nzbToSickBeard: [13:33:38] [INFO]::MAIN: Attempting to auto-detect TV fork
INFO	Tue Dec 08 2015 13:33:37	nzbToSickBeard: [13:33:37] [INFO]::MAIN: Calling SickBeard:TV to post-process:Fargo.S02E09.Castle.1080p.WEB-DL.DD5.1.H264-DRACULA
INFO	Tue Dec 08 2015 13:33:37	nzbToSickBeard: [13:33:37] [INFO]::MAIN: Auto-detected SECTION:SickBeard
INFO	Tue Dec 08 2015 13:33:37	nzbToSickBeard: [13:33:37] [INFO]::MAIN: Script triggered from NZBGet Version 16.3.
INFO	Tue Dec 08 2015 13:33:37	nzbToSickBeard: [13:33:37] [INFO]::MAIN: #########################################################
INFO	Tue Dec 08 2015 13:33:37	nzbToSickBeard: [13:33:37] [INFO]::MAIN: ## ..::[nzbToMedia.pyc]::.. ##
INFO	Tue Dec 08 2015 13:33:37	nzbToSickBeard: [13:33:37] [INFO]::MAIN: #########################################################
INFO	Tue Dec 08 2015 13:33:37	nzbToSickBeard: [13:33:37] [WARNING]::MAIN: Install ffmpeg with x264 support to enable this feature ...
INFO	Tue Dec 08 2015 13:33:37	nzbToSickBeard: [13:33:37] [WARNING]::MAIN: Failed to locate ffprobe. Video corruption detection disabled!
INFO	Tue Dec 08 2015 13:33:37	nzbToSickBeard: [13:33:37] [INFO]::MAIN: nzbToMedia Version:1cd64053b0da1d351bb6af392e1ebb904c6b6ce2 Branch:master (Linux 3.2.40)
INFO	Tue Dec 08 2015 13:33:37	nzbToSickBeard: [13:33:37] [INFO]::MAIN: No update needed
INFO	Tue Dec 08 2015 13:33:37	nzbToSickBeard: InsecureRequestWarning)
INFO	Tue Dec 08 2015 13:33:37	nzbToSickBeard: /volume1/@appstore/NzbScripts/nzbToMedia/libs/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
INFO	Tue Dec 08 2015 13:33:36	nzbToSickBeard: [13:33:36] [INFO]::MAIN: Checking if source needs an update
INFO	Tue Dec 08 2015 13:33:36	nzbToSickBeard: [13:33:36] [INFO]::MAIN: Checking database structure...
INFO	Tue Dec 08 2015 13:33:31	Executing post-process-script nzbToMedia/nzbToSickBeard.py for Fargo.S02E09.Castle.1080p.WEB-DL.DD5.1.H264-DRACULA
INFO	Tue Dec 08 2015 13:33:31	Post-process-script EMail.py for Fargo.S02E09.Castle.1080p.WEB-DL.DD5.1.H264-DRACULA successful
````

**Comment by miigotu** [comment] 2015-12-10 07:00
Telling us 10,000 times wont get it fixed any faster.

**Comment by Koal4** [comment] 2015-12-10 07:11
@miigotu oh i'm sorry that i take my free time in reporting bugs. i'm sorry to bother you with this. Maybe I should start flaming how shitty SR has become on 3rd partie websites and convince ppl to ignore the sickrage family and start using sonar instead like many other ppl do!


sjeesus... reason why I'm posting this again is that the old topic is closed. I find you work in support cases very weird because I work in support for a living. In my work closed tickets mean closed and is hardly looked at. In my work bugs are certainly not logged as support / questions. Also in my line of work the more ppl who report bugs means the issue is more common and the more ppl have problems with it the more protiriy i will receive. 

Im not expecting to get it fixed within a minute! reporting a bug and it needs to be looked at! its you problem that you get annoyed by the fact ppl are reporting bugs! If you can't keep up with bugs stop pushing damn updates every day and test it properly. As a user I don't want an update every day. I want a stable product with at least the basic fucntions to work properly. This problem was introduced a couple of weeks ago.

So again I'm sorry to bother you with bugs if you prefer  that users don't log bugs then you should remove this!@ Sorry but I feel kind of attacked by these comments as I'm only trying to help and make it bettter!

**Comment by miigotu** [comment] 2015-12-10 07:43
Taking time to report something once, and to help us debug it is one thing.

Taking time to report the same exact information over and over and write books that dont help just to "hint hint" that we arent fixing something fast enough for you? Not helpful.

BTW, your book, TL;DR

**Comment by miigotu** [comment] 2015-12-10 08:37
#111

**Closed by miigotu** 2015-12-10 08:37 UTC
Labels: Bug/Issue, Duplicate
