### ISSUE TITLE
Files don't update after a rescan

### ISSUE THREAD

**Issue by dn604** [SickRage/sickrage-issues#691] opened 2016-01-29 02:09 UTC
Hello,

First I see somehow people can post what commit version they are on etc, I don't see anywhere in the options that lists those details.  I JUST downloaded the latest master branch files and moved my database from the old SRTV.   

Have a few issues that aren't _new_, but I thought I would finally try and get some answers.

One being where SickRage lists an episode as "Snatched", but as I may have downloaded it manually or whatever, either way it was never updated that it was downloaded.  I would of hoped that after I moved the episode into the directory and clicked the "Re-scan files" button it would locate and maybe update that it was there vs just snatched?  It doesn't.....

Surely this must be possible?

Thanks!

**Comment by SickRage2** [comment] 2016-01-29 02:09
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by heymoe** [comment] 2016-01-29 04:50
You should be able to find your commit version by clicking on the Gears Icon -> Help & Info

As for the issue you described. I do what you describe where SR snatched something but for one reason or another the automated download failed. I would then manually download the correct file, rename it to the proper format and move the file into proper directory that SR expects to find the files for a particular show. After that I click the "Re-Scan Files" button and once SR is done doing it's things the episode that said it was snatched now says it's downloaded and all is well with the world.

My only guess is that you are not putting the file in to the right directory or you have it named something that SR can not decode and associate it correctly to the show. 

You will likely be asked to provide more information as well as some debug logs but what you've asked is possible.

**Comment by miigotu** [comment] 2016-01-29 05:50
You should never put files into the show folder manually. Download them and place them in the PP folder...

**Comment by dn604** [comment] 2016-01-29 05:59
The Help & Info page doesn't show anything about my commit version:
SickRage Configuration
Python Version:	2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]
SSL Version:	OpenSSL 1.0.1j 15 Oct 2014
Locale:	en_US.cp1252
 	  	 
User:	dn
Program Directory:	D:\dropbox\SickRage
Configuration File:	D:\dropbox\SickRage\config.ini
Database:	D:\dropbox\SickRage\sickbeard.db
Cache Directory:	D:\dropbox\SickRage\cache
Log Directory:	D:\dropbox\SickRage\Logs
Arguments:	['--nolaunch']
 	 
 Website:	http://sickrage.github.io/
 Wiki:	https://github.com/SickRage/sickrage-issues/wiki
 Source:	https://github.com/SickRage/SickRage/
 IRC Chat:	#sickrage-issues on irc.freenode.net

As far as my other issue.  I even go so far as to like SB rename the files first, and it still doesn't pick them up after.  Still says snatched and not downloaded etc....

Miigotu, what is the PP folder? :)

Thanks.

**Comment by labrys** [comment] 2016-01-29 06:04
@dn604 It's the post processing folder that performs the renaming and moving to your show folder.

**Comment by dn604** [comment] 2016-01-29 06:08
Ahh, thanks.

I don't use SickBeard to do my postprocessing.  

That being said, moving a file manually should certainly be ok.  Seems to work for heymoe above, not sure why that status doesn't change when I do it.

Thanks.

**Comment by neoatomic** [comment] 2016-01-29 13:48
@dn604 There should be version info on the help & info page. I added a screenshot below as example. (its at the top.)
If there isn't any, then something went wrong migrating. You might not be able to update than.

![2](https://cloud.githubusercontent.com/assets/7928052/12655768/d1c8cc50-c5fa-11e5-8bdc-18b2d2c41ead.png)

**Comment by dn604** [comment] 2016-01-30 02:06
Well I'm not sure why mine looks different.  As mentioned I recently switched from SRTV to this port.   I download a new zip file of all the files, and then I copied over my config.ini and my sickrage.db and renamed it to sickbeard.db.  Then I started it up.   All looks fine, but I assume it isn't?   Did I do something wrong, maybe the config.ini isn't compatible.   I will try a redownload again in a second, and use the current db but redo my entire config.

Looks like issue #701 has been started along the lines of my initial issue here.

**Comment by dn604** [comment] 2016-01-30 02:55
So I removed my config.ini and restarted SR, still doesn't show me anything new in Help and Info, what is causing this?

I have this message showing at the top of the main page:

Unknown current version number: If you've never used the SickRage upgrade system before then current version is not set.— Update Now

If I click Update Now, it updates and goes away but my Help and Info screen doesn't show me all the info as posted above.

Is this my old SRTV database doing this?   Other than the old config.ini and db, all files are new.  I don't understand what is going on....

Thanks.

**Comment by miigotu** [comment] 2016-01-30 07:21
"One being where SickRage lists an episode as "Snatched", but as I may have downloaded it manually or whatever, either way it was never updated that it was downloaded."

This is not a bug. You should never add files to the show folder directly. You simply place them in the PP folder if you use SR post processing, or do a manual post process and point it to the file you want moved into the show folder (manual pp works even if you dont have post processing enabled).

Reason being:
If nothing told SR a file was processed it is still waiting for the one it snatched. whether one exists in the show dir or not is irrelevant, since SR might have snatched a better quality, and it has no idea what quality the one you put into the show dir is.

If SR snatched the episode it should be processed by SOMETHING. If that is our post processor it marks it as downloaded, if that is autoProcessTV or nzbtomedia (torrenttomedia) they call our internal post processor which marks it as downloaded. If it is an external script that script needs to call our api and set it to downloaded.

**Closed by miigotu** 2016-01-30 07:21 UTC

**Comment by miigotu** [comment] 2016-01-30 13:49
The issue might be partially rectified with https://github.com/SickRage/SickRage/pull/889
