### ISSUE TITLE
[APP SUBMITTED]: <MatchTree: root=-FQM.Live.Free.or.Twi-hard> is not in list

### ISSUE THREAD

**Issue by divx-guy** [SickRage/sickrage-issues#367] opened 2015-12-30 13:56 UTC
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@ed25b12a4e71535607a72d8036e43a830e435595
No Log available with ERRORS: 
### ERROR
```
POSTPROCESSER :: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\subtitles.py", line 199, in download_subtitles
    matches = subtitle.get_matches(video, hearing_impaired=False)
  File "C:\SickRage\SickRage\lib\subliminal\providers\opensubtitles.py", line 69, in get_matches
    matches |= guess_matches(video, guess_episode_info(self.movie_release_name + '.mkv'))
  File "C:\SickRage\SickRage\lib\guessit\__init__.py", line 370, in guess_episode_info
    return guess_file_info(filename, info=info, options=options, type='episode', **kwargs)
  File "C:\SickRage\SickRage\lib\guessit\__init__.py", line 302, in guess_file_info
    result.append(_guess_filename(filename, options, **kwargs))
  File "C:\SickRage\SickRage\lib\guessit\__init__.py", line 114, in _guess_filename
    mtree = _build_filename_mtree(filename, options=options, **kwargs)
  File "C:\SickRage\SickRage\lib\guessit\__init__.py", line 127, in _build_filename_mtree
    mtree = IterativeMatcher(filename, options=merged_options, **kwargs)
  File "C:\SickRage\SickRage\lib\guessit\matcher.py", line 120, in __init__
    self._process(transformer, False)
  File "C:\SickRage\SickRage\lib\guessit\matcher.py", line 138, in _process
    transformer.process(self.match_tree, self.options)
  File "C:\SickRage\SickRage\lib\guessit\transfo\guess_release_group.py", line 223, in process
    GuessFinder(self.guess_release_group, None, self.log, options).process_nodes(mtree.unidentified_leaves())
  File "C:\SickRage\SickRage\lib\guessit\matcher.py", line 227, in process_nodes
    self.process_node(node)
  File "C:\SickRage\SickRage\lib\guessit\matcher.py", line 286, in process_node
    self.process_node(node, partial_span=relative_span, skip_nodes=next_skip_nodes)
  File "C:\SickRage\SickRage\lib\guessit\matcher.py", line 241, in process_node
    matcher_result = self.guess_func(string, node, self.options)
  File "C:\SickRage\SickRage\lib\guessit\transfo\guess_release_group.py", line 175, in guess_release_group
    if self.validate_node(leaf, node, True):
  File "C:\SickRage\SickRage\lib\guessit\transfo\guess_release_group.py", line 143, in validate_node
    if not self.validate_next_leaves(node):
  File "C:\SickRage\SickRage\lib\guessit\transfo\guess_release_group.py", line 126, in validate_next_leaves
    next_leaf = node.root.next_leaf(node)
  File "C:\SickRage\SickRage\lib\guessit\matchtree.py", line 318, in next_leaf
    return self._other_leaf(leaf, +1)
  File "C:\SickRage\SickRage\lib\guessit\matchtree.py", line 322, in _other_leaf
    index = leaves.index(leaf) + offset
ValueError: <MatchTree: root=-FQM.Live.Free.or.Twi-hard> is not in list
 [ed25b12]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment] 2015-12-30 13:56
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by medariox** [comment] 2015-12-30 14:47
Did you delete the video file while it was searching for subs? How to reproduce this?

**Comment by divxguy** [comment] 2015-12-30 14:50
hi i did nothing 
just clicking  update subs

**Comment by medariox** [comment] 2015-12-30 14:53
Do you still get that error when updating subs?

**Comment by divxguy** [comment] 2015-12-30 14:55
yup same error 
no matter what show it is updating

**Comment by medariox** [comment] 2015-12-30 15:01
Please find the video file that contains
```
-FQM.Live.Free.or.Twi-hard
```
and rename it to a proper name. Then refresh the show in question and see if yous till get that error.
Also post your debug log.

Anyway, this should probably be reported in the subliminal repo, since it seems to be a subliminal specific bug.

**Comment by divxguy** [comment] 2015-12-30 15:18
hmm now all seems to be ok 
i restarted sickrage and till now no errors

but ill will keep on eye on it

thnx for the fast reply :)

**Comment by medariox** [comment] 2015-12-30 17:21
Good to hear! Closing this for now.

**Closed by medariox** 2015-12-30 17:21 UTC
Labels: Can't reproduce, Need more info

**Comment by divx-guy** [comment] 2016-01-09 11:18
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-8-6.2.9200**
Locale: cp1252
Branch: **master**
Commit: SickRage/SickRage@7fd6c98aafe1f543bf8f96b2e370666be5412288
No Log available with ERRORS: 
### ERROR
```
SHOWQUEUE-SUBTITLE :: Traceback (most recent call last):
  File "C:\SickRage\SickRage\sickbeard\subtitles.py", line 201, in download_subtitles
    matches = subtitle.get_matches(video, hearing_impaired=sickbeard.SUBTITLES_HEARING_IMPAIRED)
  File "C:\SickRage\SickRage\lib\subliminal\providers\opensubtitles.py", line 69, in get_matches
    matches |= guess_matches(video, guess_episode_info(self.movie_release_name + '.mkv'))
  File "C:\SickRage\SickRage\lib\guessit\__init__.py", line 370, in guess_episode_info
    return guess_file_info(filename, info=info, options=options, type='episode', **kwargs)
  File "C:\SickRage\SickRage\lib\guessit\__init__.py", line 302, in guess_file_info
    result.append(_guess_filename(filename, options, **kwargs))
  File "C:\SickRage\SickRage\lib\guessit\__init__.py", line 114, in _guess_filename
    mtree = _build_filename_mtree(filename, options=options, **kwargs)
  File "C:\SickRage\SickRage\lib\guessit\__init__.py", line 127, in _build_filename_mtree
    mtree = IterativeMatcher(filename, options=merged_options, **kwargs)
  File "C:\SickRage\SickRage\lib\guessit\matcher.py", line 120, in __init__
    self._process(transformer, False)
  File "C:\SickRage\SickRage\lib\guessit\matcher.py", line 138, in _process
    transformer.process(self.match_tree, self.options)
  File "C:\SickRage\SickRage\lib\guessit\transfo\guess_release_group.py", line 223, in process
    GuessFinder(self.guess_release_group, None, self.log, options).process_nodes(mtree.unidentified_leaves())
  File "C:\SickRage\SickRage\lib\guessit\matcher.py", line 227, in process_nodes
    self.process_node(node)
  File "C:\SickRage\SickRage\lib\guessit\matcher.py", line 286, in process_node
    self.process_node(node, partial_span=relative_span, skip_nodes=next_skip_nodes)
  File "C:\SickRage\SickRage\lib\guessit\matcher.py", line 241, in process_node
    matcher_result = self.guess_func(string, node, self.options)
  File "C:\SickRage\SickRage\lib\guessit\transfo\guess_release_group.py", line 175, in guess_release_group
    if self.validate_node(leaf, node, True):
  File "C:\SickRage\SickRage\lib\guessit\transfo\guess_release_group.py", line 143, in validate_node
    if not self.validate_next_leaves(node):
  File "C:\SickRage\SickRage\lib\guessit\transfo\guess_release_group.py", line 126, in validate_next_leaves
    next_leaf = node.root.next_leaf(node)
  File "C:\SickRage\SickRage\lib\guessit\matchtree.py", line 318, in next_leaf
    return self._other_leaf(leaf, +1)
  File "C:\SickRage\SickRage\lib\guessit\matchtree.py", line 322, in _other_leaf
    index = leaves.index(leaf) + offset
ValueError: <MatchTree: root=-FQM.Live.Free.or.Twi-hard> is not in list
 [7fd6c98]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by mr-leerkotte** [comment] 2016-01-22 21:53
### INFO
Python Version: **2.7.10 (default, Dec  7 2015, 13:28:23) [GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)]**
Operating System: **FreeBSD-10.2-RELEASE-p7-amd64-64bit-ELF**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@66fa37c556784fa3b41a06bb3043bd854d165c10
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-SUBTITLE :: Traceback (most recent call last):
  File "/usr/local/share/SickRage/sickbeard/subtitles.py", line 177, in download_subtitles
    matches = subtitle.get_matches(video, hearing_impaired=sickbeard.SUBTITLES_HEARING_IMPAIRED)
  File "/usr/local/share/SickRage/lib/subliminal/providers/opensubtitles.py", line 69, in get_matches
    matches |= guess_matches(video, guess_episode_info(self.movie_release_name + '.mkv'))
  File "/usr/local/share/SickRage/lib/guessit/__init__.py", line 370, in guess_episode_info
    return guess_file_info(filename, info=info, options=options, type='episode', **kwargs)
  File "/usr/local/share/SickRage/lib/guessit/__init__.py", line 302, in guess_file_info
    result.append(_guess_filename(filename, options, **kwargs))
  File "/usr/local/share/SickRage/lib/guessit/__init__.py", line 114, in _guess_filename
    mtree = _build_filename_mtree(filename, options=options, **kwargs)
  File "/usr/local/share/SickRage/lib/guessit/__init__.py", line 127, in _build_filename_mtree
    mtree = IterativeMatcher(filename, options=merged_options, **kwargs)
  File "/usr/local/share/SickRage/lib/guessit/matcher.py", line 120, in __init__
    self._process(transformer, False)
  File "/usr/local/share/SickRage/lib/guessit/matcher.py", line 138, in _process
    transformer.process(self.match_tree, self.options)
  File "/usr/local/share/SickRage/lib/guessit/transfo/guess_release_group.py", line 223, in process
    GuessFinder(self.guess_release_group, None, self.log, options).process_nodes(mtree.unidentified_leaves())
  File "/usr/local/share/SickRage/lib/guessit/matcher.py", line 227, in process_nodes
    self.process_node(node)
  File "/usr/local/share/SickRage/lib/guessit/matcher.py", line 286, in process_node
    self.process_node(node, partial_span=relative_span, skip_nodes=next_skip_nodes)
  File "/usr/local/share/SickRage/lib/guessit/matcher.py", line 241, in process_node
    matcher_result = self.guess_func(string, node, self.options)
  File "/usr/local/share/SickRage/lib/guessit/transfo/guess_release_group.py", line 175, in guess_release_group
    if self.validate_node(leaf, node, True):
  File "/usr/local/share/SickRage/lib/guessit/transfo/guess_release_group.py", line 143, in validate_node
    if not self.validate_next_leaves(node):
  File "/usr/local/share/SickRage/lib/guessit/transfo/guess_release_group.py", line 126, in validate_next_leaves
    next_leaf = node.root.next_leaf(node)
  File "/usr/local/share/SickRage/lib/guessit/matchtree.py", line 318, in next_leaf
    return self._other_leaf(leaf, +1)
  File "/usr/local/share/SickRage/lib/guessit/matchtree.py", line 322, in _other_leaf
    index = leaves.index(leaf) + offset
ValueError: <MatchTree: root=-FQM.Live.Free.or.Twi-hard> is not in list
 [66fa37c]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
