### ISSUE TITLE
[mako error] Anime shows with special episodes page display mako error

### ISSUE THREAD

**Issue by yongbi85** [SickRage/sickrage-issues#619] opened 2016-01-24 09:50 UTC
Branch : master

Commit hash : Can't find it as Help & Info is also giving me a Mako error (another issue will be opened for that i guess), but I just updated it on 2016-01-24 (last master commit when i post this bug)

Your operating system and python version : Synology DSM 5.2-5644 Update 2 and Python 2.7.11-15

What you did : Tryed to open the anime page for Attack on Titan, Detective Conan, Fairy Tail, Garo Crimson Moon, Kamisama Kiss, Naruto Shippuden, One Piece, Saint Seiya

What happened : 
````
Mako error with error saying : 
File /usr/local/sickrage/var/SickRage/gui/slick/views/displayShow.mako:56, in render_content:
        % if int(seasonResults[-1]["season"]) == 0:
TypeError: int() argument must be a string or a number, not 'NoneType'
````

What you expected
To view the show episodes and status.

How can we reproduce your issue
Try to add one of those animes and have a Special Episode in your library (season 0)

**Comment by SickRage2** [comment] 2016-01-24 09:50
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by yongbi85** [comment] 2016-01-24 10:26
For info, i tryed remove and readd the anime, remove the anime, move the Season 0 folder elsewhere and readd the anime, still the same...

**Comment by OmgImAlexis** [comment] 2016-01-24 10:41
@medariox looks like a duplicate of the other issue.

**Comment by yongbi85** [comment] 2016-01-24 10:42
If you're talking about the backlog overview issue this one is solved, despite all those animes giving mako error msg, the backlog overview page now loads fine.

**Comment by OmgImAlexis** [comment] 2016-01-24 11:06
@yongbi85 it could be a related issue to the other though, the code below is similar to another error we had reported.

````
% if int(seasonResults[-1]["season"]) == 0:
````

**Comment by yongbi85** [comment] 2016-01-24 11:35
Yes it probably is linked to the issue #504 as the ones having the backlog issues were the ones with animes and specials mostly

**Comment by yongbi85** [comment] 2016-01-24 17:28
OK info on my version as the infos page issue is solved by switching to Sickbeard custom package.
The anime bug is still there :

SickRage Version:	Branch: master
Commit: aeffe26776f0333a59868508655dcbbfd9df33c3
Version: 2016.01.23-1
Python Version:	2.7.11 (default, Dec 17 2015, 15:58:38) [GCC 4.7.3 20130102 (prerelease)]
SSL Version:	OpenSSL 1.0.2e 3 Dec 2015
Locale:	en_US.UTF-8

**Comment by p0psicles** [comment] 2016-01-28 15:59
I seem to have the same issue on my linux machine. Can't reproduce it on my dev.
seasonResults for my show had three sqlite3 objects all with content None. So [None,None,None]. Instead of [2,1,0].

It's easily fixed in the template. Just replace: 
% if seasonResults:
with
% if seasonResults and hasattr(seasonResults[0], 'season'):
on line 54.

But then we  still don't have the root cause.
If i'm doing the query manually it gives back the correct response.

**Comment by miigotu** [comment] 2016-01-29 05:47
Fixed in https://github.com/SickRage/SickRage/issues/866

**Closed** 2016-01-29 05:48 UTC

**Comment by p0psicles** [comment] 2016-01-29 10:57
The season NULL values can cause issues everywhere. Just  a few examples:
Webapi:
2.481: sql_results = main_db_con.select("SELECT DISTINCT season FROM tv_episodes WHERE showid = ? ORDER BY season ASC", 
2.484: sql_results = main_db_con.select("SELECT DISTINCT season FROM tv_episodes WHERE showid = ? ORDER BY season DESC", 

GenericProvider:
250: 'SELECT season, episode FROM tv_episodes WHERE showid = ? AND airdate = ?', 

dailysearcher:
62: sql_results = main_db_con.select("SELECT showid, airdate, season, episode FROM tv_episodes WHERE status = ? AND (airdate <= ? and airdate > 1)", 

@miigotu @labrys 
Can't we just put a "NOT NULL" constraint on it? Then at least we can detect were thisi going wrong?

**Comment by miigotu** [comment] 2016-01-30 13:49
https://github.com/SickRage/SickRage/pull/889
