### ISSUE TITLE
Wrong Language in Metadata (nfo) after post processing 

### ISSUE THREAD

**Issue by schimi2k** [SickRage/sickrage-issues#778] opened 2016-02-05 16:17 UTC
Hello Gentlemen,
i have set my config to GERMAN and i get the german infos within the SICKRAGE GUI, but it writes the nfo files of the episodes only in ENGLISH - a fix for that would be perfect
also have some problems with "ÄÖÜ" letters ... 

but at least your version is working great except those two "small" problems so far :+1: WELL DONE

**Comment by SickRage2** [comment] 2016-02-05 16:17
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by schimi2k** [comment] 2016-02-06 08:17
ok, second try ;)
- I want configure to get GERMAN Metadata and Episode informations in my nfo files
- I get ENGLISH Text in my .nfo files instead - inside SICKRAGE i get German text of the Infos (mouse over the small "i" icon - seems the export to the nfo file is wrong ?
no errors in logfile - all seems good

Branch: latest MASTER from Feb.06.2016
Python Version:	2.7.11 (v2.7.11:6d1b6a68f775, Dec 5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
SSL Version:	OpenSSL 1.0.2d 9 Jul 2015
OS:	Windows-10-10.0.10586
Locale:	de_DE.cp1252

**Comment by miigotu** [comment] 2016-02-07 10:21
You will have to wait for someone to get around to looking at this. We are busy people and generally more serious issues take priority =P

**Comment by schimi2k** [comment] 2016-02-08 11:27
no problem, and thx for the nice answer :)

**Comment by labrys** [comment] 2016-02-08 15:07
@schimi2k It looks like the language that the show is when the .nfo is generated is the language the .nfo will be in.  It does not appear to update on a rescan, update, or language change.  Deleting the nfo and having it recreated does create it in the currently selected language though.

**Comment by neoatomic** [comment] 2016-02-08 15:10
Been testing this all afternoon.

Did a fresh install on Windows 10. Added the show [Deutschland 83.](http://dereferer.org/?http://thetvdb.com/?tab=series&id=294801)
Then went to Meta data and enabled Kodi12+ data. Checked the Show meta-data & episode meta-data.
Then created a fake *.mkv called `Deutschland 83 s01e07.mkv` to simulate that a download was there.
Did a full update and SR wrote the [tvshow.nfo](http://pastebin.com/raw/246nZG5d) & [Deutschland 83 s01e07.nfo](http://pastebin.com/raw/iYDqKvHg)
As you can see from the paste they are in German. 

So the wrong language i cant replicate. However i can confirm the special characters not being created correctly in the *nfo files. : 
`NATO-Man├╢ver, Friedensbewegung und die Neue Deutsche Welle ΓÇô der junge`

![1](https://cloud.githubusercontent.com/assets/7928052/12889201/243908e8-ce7e-11e5-85ed-6394bb5101d5.png)
![2](https://cloud.githubusercontent.com/assets/7928052/12889202/245fc154-ce7e-11e5-997b-7adeab063b44.png)

**Comment by schimi2k** [comment] 2016-02-09 19:57
first big thx 4 your help neoatomic and labrys
i can confirm that i have also the german text INSIDE SICKRAGE - but the .nfo file inside my Season folder i will get the ENGLISH text - thats what strange
here you can see what i mean:  http://imgur.com/a/Oii36

**Comment by duramato** [comment] 2016-02-09 20:41
Its working fine here even with german as a language

**Comment by neoatomic** [comment] 2016-02-09 23:48
@schimi2k Try to remove all *.nfo files from the shows folder and than do a force full update of the show, so that new *.nfo files get created. And maybe remove/re add the show.
Otherwise i cant explain it, as i tested it pretty extensive...

(And just to make sure, you don't have anther program creating those nfo files.?)

**Comment by schimi2k** [comment] 2016-02-10 06:10
thx again for your help
1. i scrape all my stuff with Ember Media Manager - but it wasnt running while i post process the test episode.  there was no .nfo file and when i post process with SICKRAGE i saw when the .nfo file was created - besides this, the nfo file of Ember is bigger, because it have more infos inside - so the new .nfo is 100% from sickrage ( i test it with 3 episodes )

2. if you dont have any issuess like this, i will try to make a complete fresh install of sickrage and add my series again - it was just curious that i have the german plot inside sickrage and the english plot inside me .nfo file... so i thought there would be maybe an export bug or so... i will report back after i test the fresh version

**Comment by labrys** [comment] 2016-02-10 12:10
The info in SickRage comes from the database.  SickRage creates the NFO from the database.  However if you have the English information in SickRage at the time the NFO is created you will of course have English in the NFOs.  It's possible that if you have English in the database and the corresponding record on TVDB in German doesn't have that data (e.g. plot) that it would retain the English for that data field.  However this doesn't sound like what you are experiencing.

**Comment by schimi2k** [comment] 2016-02-10 16:52
no sir,
i had for this example the german castle infos already in sickrage database ( like you see on my screenshots ) - then i delete the wrong nfo file and also the thumbnail to be sure of the second episode - then i rescan this tvshow and i can see in the season folder while sickrage is rescanning this tvshow that a new .nfo file and thumbnail was created ( by sickrage ! ) - when i check the .nfo file i get again the ENGLISH Plot instead of the german one 
like i post before, i will try a new fresh and clean sickrage install in the next few days ( too busy atm ) 

and thx again for the help :)

**Comment by schimi2k** [comment] 2016-02-12 09:11
ok, i test again with a clean and fresh version of latest SICKRAGE from 12.02.2016 (master branch)
fresh database with one tvshow tested ( castle ) - i have tested now german,french and spanish - everything works like a charm INSIDE Sickrage - but every generated .nfo file had the english PLOT instead of the chosen language - so i think there is maybe a small bug inside the metadata export function ?
maybe some other non english user can confirm this ?
thx again in advance

**Comment by repulse** [comment] 2016-02-12 14:14
@schimi2k Yeah, i can confirm i'm in the same case.
Fresh install of SickRage, with deleting .nfo and thumbnails previously generated, and delete/add again show in SickRage, and .nfo files still in english instead of french.

**Comment by miigotu** [comment] 2016-02-12 14:15
Patience, this is a low priority =P

**Comment by repulse** [comment] 2016-02-12 14:18
@miigotu Yeah i know, i'm just confirming it ;)

**Comment by schimi2k** [comment] 2016-02-12 17:02
sickrage is a racist ! ... ( JOKE ;) ) 
i know it too, just want to confirm it either - will wait now 
and thx again to the whole team for sickrage !

**Comment by duramato** [comment] 2016-02-12 17:07
@schimi2k `sickrage is a racist ! ... ( JOKE ;) ) ` of course xD
ok can you try changing a show language info to any other instead of german to see if it changes the nfo to that language ? (and if you change it back to german if it updates to german

**Comment by schimi2k** [comment] 2016-02-15 09:30
sorry for my late response ( had a cold )
i change to english - all infos inside sickrage get english ( titles and also the plot ) - well the .nfo file was english too - well, i think this should be normal ;)
when i change back to german, its getting german INSIDE Sickrage again ( titles and plot ) and the .nfo get the racist .nfo again ;) ( with the english plot )
but for me its okay now, because i scrape the metadata with Ember now, where i get also the video data inside the .nfo file ( resolution, audioformat etc ) - so i disable the metadata now anyway ;)
so big thx for all the help and for SICKRAGE !

**Comment by cyan** [comment] 2016-04-11 08:32
hi, im just passing there to say that i have the same problem, asking for french but having english data in nfo files.

**Comment by bemar** [comment] 2016-04-25 14:24
Hi, I'm having the same problem so I quickly check the code to find a workaround.

I think the root cause if the tvdb indexer defined in  [https://github.com/SickRage/SickRage/blob/master/sickbeard/indexers/indexer_config.py](https://github.com/SickRage/SickRage/blob/master/sickbeard/indexers/indexer_config.py)
Default indexer language is 'en'.

In all metadata classes, if sickbeard defined indexer language is different than show/ep language, the show/ep language is used to retrieved infos. But if not, the defalt config language is used... and not the sickbeard defined indexer language.
This is an example of this implementation:
```python
if indexer_lang and not indexer_lang == sickbeard.INDEXER_DEFAULT_LANGUAGE:
    lINDEXER_API_PARMS['language'] = indexer_lang
```

From what i saw, changes cannot be applied in indexer_config.py, so It seems to me there are two ways of correcting this :

- change metadata classes like so :

```python
if indexer_lang and not indexer_lang == sickbeard.INDEXER_DEFAULT_LANGUAGE:
    lINDEXER_API_PARMS['language'] = indexer_lang
else:
    lINDEXER_API_PARMS['language'] = sickbeard.INDEXER_DEFAULT_LANGUAGE
```

or

```python
lINDEXER_API_PARMS['language'] = sickbeard.INDEXER_DEFAULT_LANGUAGE
if indexer_lang and not indexer_lang == sickbeard.INDEXER_DEFAULT_LANGUAGE:
    lINDEXER_API_PARMS['language'] = indexer_lang
```

- A "dirty" way in indexer_api.py by defining default indexer language (The solution I choose for now):

```python
@property
    def api_params(self):
        if self.indexerID:
            indexerConfig[self.indexerID]['api_params']['language'] = sickbeard.INDEXER_DEFAULT_LANGUAGE
            if sickbeard.CACHE_DIR:
                indexerConfig[self.indexerID]['api_params']['cache'] = ek(os.path.join, sickbeard.CACHE_DIR, 'indexers', self.name)
            if sickbeard.PROXY_SETTING and sickbeard.PROXY_INDEXERS:
                indexerConfig[self.indexerID]['api_params']['proxy'] = sickbeard.PROXY_SETTING

            return indexerConfig[self.indexerID]['api_params']
```

- For a temporary workaround, I think it is possible to specify in general settings the "Default Indexer Language" as English, so when specifying a different language for show/ep, metadata will be in the wanted language. (But the webUI show/ep datas will be in english...)

**I know this kind of issue is low priority, but it is certainly considered as a high priority by all the non-english users ;-)**

**Comment by miigotu** [comment] 2016-04-26 00:21
first thing, we dont use this issue tracker anymore, we use the issue tracker on the main repo https://github.com/SickRage/SickRage/issues

Ill push a fix to develop shortly, you will all need to test it and let me know

**Comment by miigotu** [comment] 2016-04-26 00:43
Please test the develop branch, and open an issue in https://github.com/SickRage/SickRage/issues if it is still a problem.

**Closed by miigotu** 2016-04-26 00:43 UTC
Labels: Bug/Issue, Priority-Low

**Comment by bemar** [comment] 2016-04-27 08:22
@miigotu Thx a lot. Tested on the develop branch and it works as expected.

**Comment by miigotu** [comment] 2016-04-27 08:28
Merged to master =P
