### ISSUE TITLE
SMTP AUTH extension not supported by server. when Kodi Notifications are Enabled 

### ISSUE THREAD

**Issue by AhmedOsama** [SickRage/sickrage-issues#480] opened 2016-01-13 15:30 UTC
Branch: master
Commit: e31a2e250047c554851fe21d2465e54415345ded
Version: v5.1.1
OS: DSM 5.2 Synology 

Test Email works with no issues I tried using smtp.gmail.com and smtp.live.com both success for test email using port 587 But sickrage fails to send emails giving the error SMTP AUTH extension not supported by server

**Comment by SickRage2** [comment] 2016-01-13 15:30
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by neoatomic** [comment] 2016-01-13 15:39
Gmail is a little tricky to setup. I dont recall the exact steps, but i copy/pasted this from the wiki. : 

Email
Allows configuration of email notifications on a per show basis.
Note: If using gmail, and having this error "ERROR: SMTP AUTH extension not supported by server." , please enable this https://www.google.com/settings/security/lesssecureapps & try settings : smtp.gmail.com , port 587 , TLS , myemail.email@gmail.com , password .

**Comment by AhmedOsama** [comment] 2016-01-13 15:49
I am using hotmail as an outgoing mail server and tested with gmail too same issue I have enabled lesssecureapps and I can receive test emails with no issues but no notifications

**Comment by AhmedOsama** [comment] 2016-01-14 09:25
Email notifications stop to work once I enable Kodi Notifications

**Comment by fernandog** [comment] 2016-01-14 11:08
@AhmedOsama 
no error messages? 
enable debug logs in SR. save. stop SR. delete all log files inside ~/SickRage/Logs
start SR
reproduce error
post full logs in https://gist.github.com/

**Comment by AhmedOsama** [comment] 2016-01-14 23:24
@fernandog ,

I disabled Kodi notifications and I disabled Email notifications shutdown sickrage then navigated into the config.ini file and manually enabled them by changing the 0 to 1 started sickrage and it now works fine sickrage is able to notify kodi and send emails with no issues but for some reason that did not happen when doing it via the GUI web interface

**Comment by AhmedOsama** [comment] 2016-01-14 23:25
feel free to close the issue if you see that its the appropriate action, however I am still wondering why it didn't work when I tried to do it via the GUI

**Comment by fernandog** [comment] 2016-01-14 23:52
Try using UI again.

**Comment by AhmedOsama** [comment] 2016-01-14 23:55
sorry forgot to mention that the same issue populated again after attempting to run any changes on mail notifications or kodi however when one of them is disabled via UI the other works fine can't get both to work by setting them using the UI and once again I fixed it by manually altering the config.ini file

**Comment by fernandog** [comment] 2016-01-15 00:01
Ok. Will look into it tomorrow

**Comment by fernandog** [comment] 2016-01-16 12:32
fixed in develop

**Closed by fernandog** 2016-01-16 12:32 UTC
Labels: Bug/Issue, Fixed

**Comment by fredwu** [comment] 2016-01-27 12:57
Interesting to note that on the latest master, which has the patch, gmail sending did NOT work until I found out about this thread here and disabled Plex Media Server. Then gmail worked and re-enabled Plex and both work. :)

**Comment by ghallford** [comment] 2016-03-16 23:48
I still have this issue. Not enabling or re-enabling has allowed me to fix it. Email doesn't work with the error AUTH Extension not supported by server. I have both Kodi and Plex notifications working correctly.

**Comment by VenomXII** [comment] 2016-06-22 01:43
I am running into this issue currently, i continue to receive the SMTP Auth extension not supported by server and i have nothing else set for notifications just email. 
Any ideas?

**Comment by AhmedOsama** [comment] 2016-06-22 01:45
Mmm if I recall properly I ended up fixing it by going through the config file and setting it manually and then restarting the sickrage service      

Regards,
Ahmed




On Wed, Jun 22, 2016 at 3:43 AM +0200, "VenomXII" <notifications@github.com> wrote:












I am running into this issue currently, i continue to receive the SMTP Auth extension not supported by server and i have nothing else set for notifications just email. 

Any ideas?

**Comment by VenomXII** [comment] 2016-06-22 01:47
@AhmedOsama Yeah i fixed it, sorry i deleted my original comment because i fixed it. i had to restart the SR service. email's are coming in fine now. 
Thank you sir.
