### ISSUE TITLE
[APP SUBMITTED]: 'exceptions.ValueError' object has no attribute 'errno'

### ISSUE THREAD

**Issue by Lowmach1ne** [SickRage/sickrage-issues#1178] opened 2016-03-11 00:58 UTC
### INFO
Python Version: **2.7.5 (default, Nov 20 2015, 02:00:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]**
Operating System: **Linux-2.6.32-44-pve-x86_64-with-centos-7.2.1511-Core**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5195b784b76916a2acfe21c1fffd12f837ce0e93
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [T411] :: [T411] :: Exception generated in thread FINDPROPERS :: [T411] :: [T411]: 'exceptions.ValueError' object has no attribute 'errno' [5195b78]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators

**Comment by SickRage2** [comment] 2016-03-11 00:58
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by miigotu** [comment] 2016-03-11 02:36
You need to update and reproduce the error, otherwise it is invalid. The amount of code that changes between releases we have no idea if it was fixed in between sometimes.

From looking at the code, it is already fixed.
https://github.com/SickRage/SickRage/blob/master/sickbeard/properFinder.py#L112

**Closed by miigotu** 2016-03-11 02:36 UTC

**Comment by AubreyKloppers** [comment] 2016-04-26 19:52
### INFO
Python Version: **2.7.3 (default, Mar 13 2014, 11:03:55) [GCC 4.7.2]**
Operating System: **Linux-3.2.0-4-amd64-x86_64-with-debian-7.10**
Locale: None
Branch: **master**
Commit: SickRage/SickRage@5195b784b76916a2acfe21c1fffd12f837ce0e93
No Log available with ERRORS:
### ERROR
```
FINDPROPERS :: [TorrentDay] :: Exception generated in thread FINDPROPERS :: [TorrentDay]: 'exceptions.ValueError' object has no attribute 'errno' [5195b78]
```
---
_STAFF NOTIFIED_: @SickRage/owners @SickRage/moderators
