### ISSUE TITLE
Updating to Transmission 2.84+ breaks ability to autodownload episodes.

### ISSUE THREAD

**Issue by atomizer83** [SickRage/sickrage-issues#1071] opened 2016-02-28 18:34 UTC
Branch/Commit: Master/4ff82463f22dab0a5de34dc963327479c0d25269
OS: Raspbian
What you did: Upgraded transmission from 2.54 to 2.84+
What happened: Sickrage is unable to add torrent to transmission 2.84+ for download.
What you expected: That it would work like when using transmission 2.54.
Logs:
```
2016-02-28 18:31:34 WARNING  SEARCHQUEUE-DAILY-SEARCH :: Transmission: Unable to send Torrent [4ff8246]
2016-02-28 18:31:33 INFO     SEARCHQUEUE-DAILY-SEARCH :: Downloading XYZ from Rarbg
```

**Comment by SickRage2** [comment] 2016-02-28 18:34
Thanks for the issue report! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist
- [x] Please wrap inline logs inside \`\`\` and \`\`\` for readability

Please make sure you also read [how to create an issue](https://github.com/SickRage/sickrage-issues/blob/master/README.md) and followed all of the steps. 

The title should describe your issue. Having "SR not working" or "I get this bug" for 100 issues, isn't really helpful. We will close issues if there isn't enough information.

Sometimes the devs may seem like grunts and respond with short answers. This isn't (always) because the dev hates you, but because he's on mobile or busy fixing bugs. If something isn't clear, please let us know, and this bot may get updated to automatically answer you.

Thanks!

**Comment by atomizer83** [comment] 2016-02-28 19:04
More info:
Using the "Testing" function when setting up transmission in SR says the connection is successfull.
The "Manage Torrents" is also not working correctly after the update of transmission. Kind of hard to explain but the open, pause and download buttons are there and steady but the torrents that are seeding and beeing downloaded are flickering at 1 second intervals. One second that are visible and the other they are not. I'm not able to control anything in transmission this way either because of the flickering.

Just to clearify: Transmission via browser works perfectly fine. So this behaivor is only seen then access through SR.

**Comment by atomizer83** [comment] 2016-02-28 19:04
Now with debug logs:
2016-02-28 19:53:42 WARNING  SEARCHQUEUE-MANUAL-302973 :: Transmission: Unable to send Torrent [4ff8246]
AA
2016-02-28 19:53:42 DEBUG    SEARCHQUEUE-MANUAL-302973 :: Transmission: Response to POST request is {"arguments":{},"result":"download directory path is not absolute"}
2016-02-28 19:53:42 DEBUG    SEARCHQUEUE-MANUAL-302973 :: Transmission: Requested a POST connection to url http://x.x.x.x:9091/transmission/rpc with Params: None Data: {"arguments": {"paused": 0, "download-dir": "", "filename": "magnet:?xt=urn:btih:61facfdfdafecf0bde...
AA
2016-02-28 19:53:42 DEBUG    SEARCHQUEUE-MANUAL-302973 :: Transmission: Response to POST request is {"arguments":{"alt-speed-down":200,"alt-speed-enabled":false,"alt-speed-time-begin":540,"alt-speed-time-day":127,"alt-speed-time-enabled":false,"alt-speed-time-end":1020,"alt-speed-up":10,"blocklist-enabled":false,"blocklist-size":393547,"blocklist-url":"http://www.example.com/blocklist","cache-size-mb":4,"config-dir":"/var/lib/transmission-daemon/info","dht-enabled":true,"download-dir":"/mnt/lager/download","download-dir-free-space":90776109056,"download-queue-enabled":true,"download-queue-size":6,"encryption":"preferred","idle-seeding-limit":30,"idle-seeding-limit-enabled":false,"incomplete-dir":"/mnt/lager/download","incomplete-dir-enabled":false,"lpd-enabled":false,"peer-limit-global":240,"peer-limit-per-torrent":90,"peer-port":37784,"peer-port-random-on-start":false,"pex-enabled":true,"port-forwarding-enabled":false,"queue-stalled-enabled":true,"queue-stalled-minutes":30,"rename-partial-files":true,"rpc-version":15,"rpc-version-minimum":1,"script-torrent-done-enabled":true,"script-torrent-done-filename":"/var/lib/transmission-daemon/info/scripts/SRpostprocess.sh","seed-queue-enabled":false,"seed-queue-size":10,"seedRatioLimit":2,"seedRatioLimited":false,"speed-limit-down":850,"speed-limit-down-enabled":true,"speed-limit-up":30,"speed-limit-up-enabled":true,"start-added-torrents":true,"trash-original-torrent-files":false,"units":{"memory-bytes":1024,"memory-units":["KiB","MiB","GiB","TiB"],"size-bytes":1000,"size-units":["kB","MB","GB","TB"],"speed-bytes":1000,"speed-units":["kB/s","MB/s","GB/s","TB/s"]},"utp-enabled":true,"version":"2.84+ (14684)"},"result":"success"}
2016-02-28 19:53:42 DEBUG    SEARCHQUEUE-MANUAL-302973 :: Transmission: Requested a POST connection to url http://x.x.x.x:9091/transmission/rpc with Params: None Data: {"arguments": {}, "method": "session-get"}
2016-02-28 19:53:42 DEBUG    SEARCHQUEUE-MANUAL-302973 :: Calling Transmission Client

**Comment by atomizer83** [comment] 2016-02-28 20:16
Ok, so by looking at the debug logs I gathered that the problems was to do with the download path. I was relying on the one set in transmission (which is still the same as on v2.54) and thus the download path in SR was blank. (Under Search Settings -> Torrent Search -> "Downloaded files location")
As stated below the field, Sickrage will use the one set in transmission if I leave it blank.

I tried setting this to the same path as used in transmission and bingo, downloads from sickrage are now working again.

So consider this a workaround and I suggest you look into the interoperability with transmission 2.84+ as it seems kind of broken.

Thanks.

**Comment by miigotu** [comment] 2016-02-28 23:05
I have been using 2.84-0.2 reliably.

About the blank file location, that isnt recommended anyways, SR should always have it's own download folder (different than the default) to prevent PP errors.

**Comment by rmbleeker** [comment] 2016-03-02 11:26
@miigotu actually this error seems legit. I upgraded Transmission from version 2.84 to 2.90 yesterday, and today had these warnings in my log:

```
2016-03-02 12:07:00 SEARCHQUEUE-DAILY-SEARCH :: Transmission: Unable to send Torrent [ace5e56]
2016-03-02 09:25:18 SEARCHQUEUE-BACKLOG-295721 :: Transmission: Unable to send Torrent [ace5e56]
2016-03-02 09:15:14 SEARCHQUEUE-BACKLOG-281485 :: Transmission: Unable to send Torrent [ace5e56]
```

I've been using 2.84 reliably for a long time as well, 2.90 came out earlier this week and it seems like they changed something. On the config page in SR the "test connection" button still reports `Success: Connected and Authenticated`. You might want to take a look since 2.90 is already in their official PPA and I'm sure more repo's will pick it up soon, so more people might run into this error.

**Comment by rmbleeker** [comment] 2016-03-02 11:59
The (error) message `"download directory path is not absolute"` plus @miigotu remark about leaving the file location blank being unsupported triggered me to set the **Downloaded files location** under **Config** -> **Search Settings** -> **Torrent Search**. This caused torrents to be added to Transmission 2.90 succesfully. 

I still think this is a bug though, as the behaviour clearly changed. I'm just not sure if it's a bug in SickRage or in the new Transmission release.

**Comment by atomizer83** [comment] 2016-03-02 16:35
Also worth mentioning from the releasenotes of transmission 2.90:
Require absolute paths in RPC requests

Might have something to do with it?

**Comment by rmbleeker** [comment] 2016-03-02 19:15
Looks like it, yeah. When browsing through the [issues closed in the 2.90 release](http://trac.transmissionbt.com/query?milestone=2.90&group=component&order=severity) I came across several that hinted at problems with empty, relative or even invalid paths when adding downloads through RPC requests. So I guess we'll just have to live with the fact that we need to supply an absolute path when adding torrents.

https://trac.transmissionbt.com/ticket/5517
https://trac.transmissionbt.com/ticket/5802
https://trac.transmissionbt.com/ticket/5825

**Comment by rmbleeker** [comment] 2016-03-02 19:43
I got into contact with the Transmission developers on IRC and they told me that Transmission validates the path if the "path" key is send in the RPC request, and this must be an absolute path since 2.90. However, if you omit the "path" key from the request Transmission will just use the default download directory.

@miigotu would it be possible to make a change in SickRage to not send an empty "path" key in the RPC request when the **Downloaded files location** is empty, but instead leave it out entirely, so that Transmission will use it's default download directory?

**Comment by miigotu** [comment] 2016-03-02 21:20
Yes, I will take care of this lol, gimme some time.

**Comment by rmbleeker** [comment] 2016-03-02 21:47
I think Fernando is already working on something? Not sure but I got an email with a link to https://github.com/pymedusa/SickRage/pull/75

**Comment by atomizer83** [comment] 2016-03-02 22:04
Then the question is wether sub 1.84 versions will accept omitting the path key or if you would have to handle some detection of versions in SR.

rmbleeker, btw, do the webaccess to transmission through SR work for you?

Thanks to both of you for looking into this. I appreciate it. :)

**Comment by miigotu** [comment] 2016-03-02 22:56
@rmbleeker pymedusa and this repo are not the same. I have it fixed here, just going to commit a bunch of stuff at one time.

**Comment by rmbleeker** [comment] 2016-03-02 23:13
@atomizer83 I never access Transmission through SR, but just to test it for you I clicked **Manage** -> **Manage Torrents**. Yes it works fine, no flickering and all the buttons work.

**Comment by atomizer83** [comment] 2016-03-03 18:40
Ok, thanks for the info.

**Comment by miigotu** [comment] 2016-03-04 09:47
Fixed in develop

**Closed by miigotu** 2016-03-04 09:47 UTC

**Comment by CuoreSportivo** [comment] 2016-03-09 10:34
Hello everyone, 
I hope that I am not writing this post in a the wrong, thread, so sorry in advance for any inconvenience.

I have transmission (without GUI) installed on a VM running Ubuntu, so that it acts as torrent server. On my main PC, I am using Transmission Remote GUI.

Everything was working fine for about two years, until I upgraded to version 2.90. Since then I am also getting the "download path is not absolute" error message, making it unable to download torrents. Today I upgraded to version 2.92, but still, the problem is present.

If I am posting this in the wrong section, does anyone know if (and how) I can contact transmission devs in order to provide them with the necessary info about his issue?

**Comment by atomizer83** [comment] 2016-03-09 10:47
I'm not sure wether this is fixed or not. As I understand it, it should be changed in Sickrage how it communicates with Transmission. Although Transmission were the ones to change what they expect in the communication.

Anyway, for a workaround you can put the path of your download folder into Sickrage and it will work until it is fixed.

Go to Search Settings -> Torrent Search -> Downloaded files location and put in the absolute path to your download folder like for example "/mnt/data/download"

Should work for now.

**Comment by miigotu** [comment] 2016-03-09 11:33
https://github.com/SickRage/sickrage-issues/issues/1071#issuecomment-192211276

**Comment by xanview** [comment] 2016-04-04 12:48
This issue is still active in 2.92 - any workaround?

**Comment by miigotu** [comment] 2016-04-04 13:10
SickRage has no issue sending to transmission

**Comment by xanview** [comment] 2016-04-04 13:22
Ah, sorry, I thought this was the issues list for Transmission, not SickRage, my bad.

**Comment by miigotu** [comment] 2016-04-04 18:13
np
